### ISSUE TITLE
sign up and repeat-password too close

### ISSUE THREAD

**Issue by edwazhao** [d33pspace/RenewalMgtApp-Html#1]
sign up and repeat-password too close to show error text

https://d33pspace.github.io/RenewalMgtApp-Html/app/sign_up.html

![image](https://user-images.githubusercontent.com/11383105/132149307-ba6dca5d-bbc4-4a06-8ca3-c94cd9a5afab.png)

**Comment by d33pspace** [comment]
@edwazhao I can't test the error message but this page seems to have been updated. Can you test and confirm?

Sign up: https://d33pspace.github.io/RenewalMgtApp-Html/app/sign_up.html

**Comment by edwazhao** [comment]
Thank you for fixing it.
