### ISSUE TITLE
Account page - align modal window

### ISSUE THREAD

**Issue by d33pspace** [d33pspace/RenewalMgtApp-Html#10]
![Screenshot 2021-09-07 092739](https://user-images.githubusercontent.com/13606352/132270603-942367e7-35b3-4921-ba24-26e210125845.png)

**Comment by d33pspace** [comment]
@MariiaBubley I cannot find how to reproduce this page in the HTML templates. Can you please check, and if it is not corrected, please provide a link to the HTML template from this menu: https://d33pspace.github.io/RenewalMgtApp-Html/app/

**Comment by MariiaBubley** [comment]
@d33pspace I can't find it too. This page is a User profile
https://www.figma.com/file/3DZItCETG2QIvRYnlQvMyn/Renewal-Mobile-App?node-id=570%3A2851

**Comment by d33pspace** [comment]
@academws Can you please confirm the alignment of the modal window was corrected? If possible, please demonstrate how to test this easily. If not, for this simple matter your confirmation is acceptable.
