### ISSUE TITLE
Behavior overview - padding

### ISSUE THREAD

**Issue by d33pspace** [d33pspace/RenewalMgtApp-Html#11]
![Screenshot 2021-09-07 092858](https://user-images.githubusercontent.com/13606352/132270687-d3e4560a-9ff8-4814-abe2-f9ead94bff26.png)

**Comment by d33pspace** [comment]
@MariiaBubley Comment from the front-end designer is: "you fixed it, it was 8 in the design. Now you want us to do 16, but the developer sees 24 in the design. What is the size right?"

**Comment by MariiaBubley** [comment]
@academws here we use component (from page 🦄Organisms) - this component has inner padding - 8px. But page margin is 16px, so 8px+16px=24px. Please look at the mockups more attentively.
![image](https://user-images.githubusercontent.com/89512026/132523873-8872214c-9f05-4a14-bc49-5a948bd3b519.png)

**Comment by d33pspace** [comment]
@MariiaBubley This page has been updated, please confirm the edits are correct. 

Behavior overview: https://d33pspace.github.io/RenewalMgtApp-Html/app/reports_behavior_overview.html

**Comment by MariiaBubley** [comment]
👌🏼

**Comment by MariiaBubley** [comment]
But there still is a problem
https://d33pspace.github.io/RenewalMgtApp-Html/app/guest_profile_behavior.html

**Comment by d33pspace** [comment]
@academws Please fix margin spacing on guest_profile_behavoir.html

**Comment by d33pspace** [comment]
@MariiaBubley This is fixed. Please confirm.

**Comment by MariiaBubley** [comment]
👌🏼
