### ISSUE TITLE
Main page - sidebar

### ISSUE THREAD

**Issue by d33pspace** [d33pspace/RenewalMgtApp-Html#12]
![edit-3](https://user-images.githubusercontent.com/13606352/132270980-8cd3a988-2701-47c3-8059-af54d72aaa20.jpg)

**Comment by d33pspace** [comment]
@MariiaBubley The front-end developer's comment is: "from right to left the developer cannot create the animation here - you have a wrapper on the desktop. It means there are gray fields on the sides, and it will move from the end of the side." Can you review and comment please?

**Comment by MariiaBubley** [comment]
@academws  as I know, possible to make different kind of animation. And I also don't understand why there are grey fields? It is not correct and you should remove them.

**Comment by d33pspace** [comment]
@MariiaBubley Hi Mariia... I believe the gray fields (on right and left) are to accommodate use on desktop. They should be visible only on large browser size. What do you think about bottom to top animation instead of top to bottom?

**Comment by MariiaBubley** [comment]
@d33pspace If you ok with it, I agree)

**Comment by d33pspace** [comment]
The menu animation has been updated from top to bottom (thank you!) but I am leaving this issue open until the tablet container discussion is resolved (#24).
