### ISSUE TITLE
Main page - gap in open menu

### ISSUE THREAD

**Issue by d33pspace** [d33pspace/RenewalMgtApp-Html#13]
![edit-4](https://user-images.githubusercontent.com/13606352/132271008-e53741ab-a342-4fbd-ae2e-c55ff0f5528a.jpg)

**Comment by d33pspace** [comment]
@MariiaBubley This looks good to me now. Please check:

Main page: https://d33pspace.github.io/RenewalMgtApp-Html/app/main_page.html#

**Comment by MariiaBubley** [comment]
ok, but sidebar can be better
