### ISSUE TITLE
New Guest - input styles

### ISSUE THREAD

**Issue by d33pspace** [d33pspace/RenewalMgtApp-Html#14]
![Screenshot 2021-09-07 093536](https://user-images.githubusercontent.com/13606352/132271088-4c289dd2-ad59-40cd-bf7a-0544aa4475fc.png)

**Comment by d33pspace** [comment]
@MariiaBubley This has been updated, please check.

**Comment by MariiaBubley** [comment]
@d33pspace yes, now it is fine
