### ISSUE TITLE
New item - align modal window

### ISSUE THREAD

**Issue by d33pspace** [d33pspace/RenewalMgtApp-Html#15]
![Screenshot 2021-09-07 093656](https://user-images.githubusercontent.com/13606352/132271172-1c4962d2-02fd-42a2-b696-8fe39ee6b12f.png)

**Comment by d33pspace** [comment]
@MariiaBubley Looks good to me, please confirm:

New Item page: https://d33pspace.github.io/RenewalMgtApp-Html/app/new_item.html

**Comment by MariiaBubley** [comment]
cool
