### ISSUE TITLE
Reports - change header color

### ISSUE THREAD

**Issue by d33pspace** [d33pspace/RenewalMgtApp-Html#16]
![Screenshot 2021-09-07 093728](https://user-images.githubusercontent.com/13606352/132271223-429e3d7e-6f04-44b5-a25f-715f1d498dc7.png)

**Comment by d33pspace** [comment]
@MariiaBubley This is fixed, please confirm (I only tested reports_behavior)

Reports - Behavior: https://d33pspace.github.io/RenewalMgtApp-Html/app/reports_behavior.html

**Comment by MariiaBubley** [comment]
👌🏼
