### ISSUE TITLE
Main page

### ISSUE THREAD

**Issue by d33pspace** [d33pspace/RenewalMgtApp-Html#17]
![Screenshot 2021-09-07 094107](https://user-images.githubusercontent.com/13606352/132271511-b030519a-3961-4298-8023-636b2c84ac82.png)

**Comment by d33pspace** [comment]
@MariiaBubley I believe this is fixed, but I only tested Behavior overview page. Can you please confirm:

Behavior overview: https://d33pspace.github.io/RenewalMgtApp-Html/app/reports_behavior_overview.html

**Comment by MariiaBubley** [comment]
@d33pspace Users also have to open with a tap on the user's line.
![image](https://user-images.githubusercontent.com/89512026/132983673-19dce5ed-16eb-4c05-a1d0-f6bc3072ff1e.png)
https://d33pspace.github.io/RenewalMgtApp-Html/app/users_list.html

all item's lines too (in all pages 
![image](https://user-images.githubusercontent.com/89512026/132983718-81f0207e-cb14-4add-b3af-20765feee6a8.png)
https://d33pspace.github.io/RenewalMgtApp-Html/app/item_catalogue.html
https://d33pspace.github.io/RenewalMgtApp-Html/app/return_page.html#
https://d33pspace.github.io/RenewalMgtApp-Html/app/take_page.html

Guests too (exept right area with other functions)
![image](https://user-images.githubusercontent.com/89512026/132983763-ffb4078a-21ea-4cdb-8c49-1addae342c1f.png)
https://d33pspace.github.io/RenewalMgtApp-Html/app/main_page.html
https://d33pspace.github.io/RenewalMgtApp-Html/app/guest_list.html

**Comment by d33pspace** [comment]
@academws Please fix tap on line response for the six additional pages here.

**Comment by d33pspace** [comment]
https://d33pspace.github.io/RenewalMgtApp-Html/app/users_list.html
- tap on line opens user profile

https://d33pspace.github.io/RenewalMgtApp-Html/app/item_catalogue.html 
- tap on line opens edit item

https://d33pspace.github.io/RenewalMgtApp-Html/app/return_page.html# 
- tap on line checks box (but trash and lost can be tapped on also)

https://d33pspace.github.io/RenewalMgtApp-Html/app/take_page.html 
- in "most commonly used" list and "full clothing list" moves item to "laundry list." 
- no need for tap on line function in laundry list.

https://d33pspace.github.io/RenewalMgtApp-Html/app/main_page.html
- in "in-service list" opens return page
- in "waiting list" moves Guest to "in-service" list (we are discussing if animation is necessary)
- in "finished list" opens Guest Profile.
- the meal icon in all lists can be tapped on individually and it changes color

https://d33pspace.github.io/RenewalMgtApp-Html/app/guest_list.html
- opens Guest profile

**Comment by AnKar112** [comment]
https://d33pspace.github.io/RenewalMgtApp-Html/app/users_list.html - that's not really 'open' as I understand. It lead you to the user profile page, so it's a link. If it somehow's 'open', I need a design for that. 
https://d33pspace.github.io/RenewalMgtApp-Html/app/item_catalogue.html - the same
https://d33pspace.github.io/RenewalMgtApp-Html/app/guest_list.html - the same
https://d33pspace.github.io/RenewalMgtApp-Html/app/return_page.html - done

https://d33pspace.github.io/RenewalMgtApp-Html/app/take_page.html - I didn't think that it works so easy, because as I understand, this page will contain some functionality like "category with items inside". For now we have only front part of them, and I really didn't think we can do it now, because all this functionality is need, with backend part. I think, your developer should do this. 

https://d33pspace.github.io/RenewalMgtApp-Html/app/main_page.html :
in "in-service list" opens return page - as I understand, this is link too. 
in "finished list" opens Guest Profile - same
in "waiting list" moves Guest to "in-service" list (we are discussing if animation is necessary) - done
the meal icon in all lists can be tapped on individually and it changes color - done

**Comment by d33pspace** [comment]
@AnKar112 @academws Thanks for these changes! It's looking great!

https://d33pspace.github.io/RenewalMgtApp-Html/app/users_list.html 
https://d33pspace.github.io/RenewalMgtApp-Html/app/guest_list.html
^ For these two pages can you please link to any blank page so we can just test the tap on line functionality?

https://d33pspace.github.io/RenewalMgtApp-Html/app/item_catalogue.html
^ We are discussing logic for this page with UX designer, please wait.

https://d33pspace.github.io/RenewalMgtApp-Html/app/return_page.html
^ This looks great! But... 
     (1) Both Trash and Lost icons cannot be active at the same time. If Trash is active and Lost is tapped, Trash becomes inactive. If Lost is active and Trash is tapped, Lost becomes inactive. 
     (2) Unless the user taps exactly on the Trash or Lost icons, the line is tapped instead. Can we do the tap fields more like this?
![Screenshot 2021-09-15 104731](https://user-images.githubusercontent.com/13606352/133362303-0bb353db-401e-4304-b219-5af9676676a3.png)

https://d33pspace.github.io/RenewalMgtApp-Html/app/take_page.html 
^ I understand your meaning, but in this case can we please explain the logic so you can demonstrate the UI feature? 
     (1) If an item in the MOST COMMONLY USED list is tapped, it is added to the LAUNDRY LIST. (It also stays in the MOST COMMONLY USED list.) 
     (2) There are two types of items that can be added from the FULL CLOTHING LIST, (a) any sub-item, (b) any item that does not have any sub-items.
          (a) If any sub-item in the FULL CLOTHING LIST is tapped, it is added to the LAUNDRY LIST. It also stays in the FULL CLOTHING LIST list.
          (b) Please remove the sub-items from Shorts in the FULL CLOTHING LIST. Shorts is an example of an item that does not have sub-items. And because it does not have sub-items, when it is tapped it is added to the LAUNDRY LIST. It also stays in the FULL CLOTHING list.

https://d33pspace.github.io/RenewalMgtApp-Html/app/main_page.html
^ You are correct about In-Service list and Finished list are links, but like above, can you please just link to a blank page so we can test the tap-on-line functionality?
- And one bug... when you tap on someone in the Waiting list to move them to the In-Service list, the meal icon cannot be made active/inactive any longer. (Also, please use full tap fields as I explained above.)

**Comment by AnKar112** [comment]
https://d33pspace.github.io/RenewalMgtApp-Html/app/users_list.html - done
https://d33pspace.github.io/RenewalMgtApp-Html/app/guest_list.html - done
https://d33pspace.github.io/RenewalMgtApp-Html/app/return_page.html - done 
https://d33pspace.github.io/RenewalMgtApp-Html/app/main_page.html - done

https://d33pspace.github.io/RenewalMgtApp-Html/app/take_page.html - not really simple task, need some time to overthink about it, will try to do it tomorrow

**Comment by d33pspace** [comment]
@AnKar112 @academws Sorry - again I'm not seeing it. Maybe didn't update the repository yet?

**Comment by d33pspace** [comment]
@AnKar112 @academws 

users_list - looks good!
guest_list - looks good!
return_page - perfect!

main_page - small problem:
- When you tap on the meal icon in In-Service List or Finished List, It both activates the icon AND links to another page. It should only activate the icon. If you tap on the rest of the line, the link should open. Waiting List works as expected. 

take_page - understood. please let me know if I can help you further understand the process. all we need of course is sufficient demonstration of UI features, not backend logic.

**Comment by AnKar112** [comment]
main_page - fixed

**Comment by d33pspace** [comment]
@AnKar112 @academws 
- This is still not quite right (or maybe you have not pushed the change yet)... (1) Tap on someone in the Waiting list to move them to the In-Service list (2) tap on meal. All that should happen is the meal should become inactive/active. Instead a link is also opened.
- Please make square click/tap fields in all three lists like this:
![Screenshot 2021-09-17 094951](https://user-images.githubusercontent.com/13606352/133711003-829b8507-4e28-4360-a1c2-dc5afaa0fcde.png)

**Comment by AnKar112** [comment]
All done

**Comment by d33pspace** [comment]
@AnKar112 @academws 
The last update to main_page says yesterday. Perhaps you need to push?

Also:
- Change the icon on the FAB (menu in lower right) when closed should look like this (below). It means "add guest".
![133755792-1d98da73-e46b-42e4-b015-631ccf5c85ff](https://user-images.githubusercontent.com/13606352/133866248-0009574b-4c53-482e-bfbb-ce7cbc0055bd.png)

**Comment by AnKar112** [comment]
>The last update to main_page says yesterday. Perhaps you need to push? - no, I wasn't changing html file, I changed JS file
Change the icon on the FAB (menu in lower right) when closed should look like this (below). It means "add guest". - done

**Comment by d33pspace** [comment]
@AnKar112 @academws 
Icon change and Serve all button look and work great. However, still two problems...

- Tap fields are still not square. It should not be possible to click/tap just outside the meal to fire the "tap on line" function.
![Screenshot 2021-09-17 094951](https://user-images.githubusercontent.com/13606352/133711003-829b8507-4e28-4360-a1c2-dc5afaa0fcde.png)

- (1) Tap on someone in Waiting List to move them to In-Service List. (2) Tap on the meal. The result is the meal icon is activated AND the return page is opened. But only the meal should be activated.

**Comment by d33pspace** [comment]
@AnKar112 @academws 
I'm so sorry I'm still seeing the problem I keep referring to. Please allow me to explain again.

Please take these exact steps on main_page to observe it:
https://d33pspace.github.io/RenewalMgtApp-Html/app/main_page.html

(1) Tap on a Guest in the Waiting list to move them to the In-Service list.
(2) Tap on the meal icon of the Guest that you just moved to the In-Service list.

The result is: (a) The meal icon activates, and (b) the User is directed to the return page.

Result (a) is correct, result (b) is incorrect. The User should not be directed to the return page.

I hope this makes it clear. 😊

**Comment by AnKar112** [comment]
Sorry, get you wrong last time. I mean, I found and fixed the bug last time, but it was another bug :)
Fixed it too, check it please
