### ISSUE TITLE
Reports page - add padding before title

### ISSUE THREAD

**Issue by d33pspace** [d33pspace/RenewalMgtApp-Html#18]
![Screenshot 2021-09-07 094231](https://user-images.githubusercontent.com/13606352/132271582-19b7ec79-ebf2-4fbc-b8c4-0ed0837a2d22.png)

**Comment by d33pspace** [comment]
@MariiaBubley This appears to be fixed. Please confirm:

Reports - Main: https://d33pspace.github.io/RenewalMgtApp-Html/app/reports_main.html

**Comment by MariiaBubley** [comment]
👌🏼
