### ISSUE TITLE
Return page - fix background shear and FAB animation

### ISSUE THREAD

**Issue by d33pspace** [d33pspace/RenewalMgtApp-Html#19]
![Screenshot 2021-09-07 094330](https://user-images.githubusercontent.com/13606352/132271662-e102ffd0-c833-47af-a820-1c1364cd09d3.png)

**Comment by d33pspace** [comment]
@MariiaBubley This appears to be fixed - can you confirm?

Return page: https://d33pspace.github.io/RenewalMgtApp-Html/app/return_page.html

**Comment by MariiaBubley** [comment]
@d33pspace yes, now this background looks fine

**Comment by MariiaBubley** [comment]
@d33pspace But here still a problem
![image](https://user-images.githubusercontent.com/89512026/132984055-966775c2-f35b-4079-a147-86a15be1cce4.png)
https://d33pspace.github.io/RenewalMgtApp-Html/app/give_page.html

**Comment by d33pspace** [comment]
@MariiaBubley I see the misalignment in your screenshot, but I cannot reproduce it. See my screenshots from desktop and mobile below. These look correct to me. Can you provide more information on how to reproduce the misalignment you are seeing so we can research further?


![Screenshot 2021-09-13 111324](https://user-images.githubusercontent.com/13606352/133018716-62e35435-8063-4c6a-9bec-e821819def89.png)
![Screenshot_2021-09-13-11-15-11-305_com android browser](https://user-images.githubusercontent.com/13606352/133018720-62309064-5207-47e7-8b69-0d8c8e819eb4.jpg)

**Comment by AnKar112** [comment]
Couldn't reproduce it too. Looking like you use old version, it was fixed some days ago.

**Comment by d33pspace** [comment]
@MariiaBubley Can you please test this on your device/browser and if there is still an issue provide details so we can research it. This looks fine on my devices.

**Comment by d33pspace** [comment]
We'll deal with this in issue #9
