### ISSUE TITLE
Take page save icon is not changed

### ISSUE THREAD

**Issue by edwazhao** [d33pspace/RenewalMgtApp-Html#2]
https://d33pspace.github.io/RenewalMgtApp-Html/app/take_page.html
1:
![image](https://user-images.githubusercontent.com/11383105/132149394-c5056ccf-9263-4a2e-b841-a88bea6080a6.png)
![image](https://user-images.githubusercontent.com/11383105/132149484-cae0eb5e-5b60-4bc9-a599-7a080210c6df.png)

2: we need the trash icon
![image](https://user-images.githubusercontent.com/11383105/132149734-9ded571f-63ef-499c-a0dc-239c35f658fb.png)

**Comment by d33pspace** [comment]
@edwazhao I'm not sure what's going on here. Can you check to see if changes have been made and if not, explain clearly what the issue is (and how to test using the templates, if possible).

**Comment by d33pspace** [comment]
Question from @academws Can you explain to me the logic and appearing the check and trash icon, please?

- If the pencil is tapped, the user can edit the laundry tag number (in this case 336). 
- When the pencil is tapped, the pencil should turn to a check. When the check is tapped, editing is complete and the pencil reappears.
- The trash can turns red when it is tapped. This means an item (in this case socks) was taken from the Guest, then thrown in the trash.
- (The check and the trash do not have anything to do with one another.)

**Comment by d33pspace** [comment]
Hi @AnKar112 @academws These changes look nice, thank you! 

However, for me, when the input field appears, it extends beyond the page into the grey frame. And actually, the laundry tag is maximum three characters, for example, 999. Please make the input field shorter.

![Screenshot 2021-09-14 183659](https://user-images.githubusercontent.com/13606352/133243718-ef5dbfb3-41dc-418e-8b84-592a9b96a479.png)

**Comment by AnKar112** [comment]
Can you provide me screen resolution? I couldn't recreate inout width issue. 
I make max length of field 4 symbols (tag + hash)

**Comment by d33pspace** [comment]
@AnKar112 @academws I am using Firefox desktop/mobile and it does this no matter the width of the browser. In Chrome it looks good. If this is not an easy fix don't worry about it, as long as it looks good in Chrome we are good.

**Comment by AnKar112** [comment]
That's not hard, you give me all information I need :)
Fixed for firefox too, check please.

**Comment by d33pspace** [comment]
@AnKar112 @academws Thank you! But no change on my end and the file doesn't seem to be updated. Maybe you didn't push the change?

**Comment by AnKar112** [comment]
Strange, it wasn't pushed. Check it again, please, now it should be ok.

**Comment by d33pspace** [comment]
@edwazhao @MariiaBubley The edit laundry tag features here look good to me. Can you confirm? By the way, more UI functionality needs to be added to this page, but that is being tracked under issue #17 .

**Comment by edwazhao** [comment]
Looks good to me, thank you
