### ISSUE TITLE
Take page - change font

### ISSUE THREAD

**Issue by d33pspace** [d33pspace/RenewalMgtApp-Html#21]
![Screenshot 2021-09-07 094635](https://user-images.githubusercontent.com/13606352/132271851-b25ba526-0089-42ba-9833-e1d7468a78d9.png)

**Comment by d33pspace** [comment]
@MariiaBubley I do not see a smaller font in the mockup, can you please provide a screenshot?

Take page: https://d33pspace.github.io/RenewalMgtApp-Html/app/take_page.html

**Comment by MariiaBubley** [comment]
@d33pspace now in this link (https://d33pspace.github.io/RenewalMgtApp-Html/app/take_page.html), everything is correct. But on the screenshot was a bigger font.
