### ISSUE TITLE
Font for links

### ISSUE THREAD

**Issue by d33pspace** [d33pspace/RenewalMgtApp-Html#22]
Hi @MariiaBubley ... question from FD... The Public Sans font is used here. Do I understand right?

![kiss_26kb 1631139091](https://user-images.githubusercontent.com/13606352/132642395-8d17eedd-07e0-4a10-9f8f-9e1b975ea1a8.png)

**Comment by MariiaBubley** [comment]
@d33pspace oh, no! this is a mistake! We use only Noto Sans

**Comment by d33pspace** [comment]
@academws @AnKar112 Please change this font to Noto Sans.

**Comment by d33pspace** [comment]
@AnKar112 @academws Can you please point out this template so we can verify? Thank you!

**Comment by AnKar112** [comment]
You can find it at the bottom of index page http://ipic.su/img/img7/fs/kiss_17kb.1631637102.png
Then click this button http://ipic.su/img/img7/fs/kiss_24kb.1631637130.png
