### ISSUE TITLE
Search and sort

### ISSUE THREAD

**Issue by edwazhao** [d33pspace/RenewalMgtApp-Html#23]
1. There are two entry point can go to GuestList, see screenshot below, will the different entry point change the behavior of the guest list?
![image](https://user-images.githubusercontent.com/11383105/132786760-5413999d-3ac0-4064-b4b6-dc538d1c21da.png)

2. There are three possible pages to go when user **click** one guest in the Guest List
    a. Add the guest to waiting list https://d33pspace.github.io/RenewalMgtApp-Html/app/main_page.html
    b. Edit the guest https://d33pspace.github.io/RenewalMgtApp-Html/app/edit_guest.html
    c. View guest profile https://d33pspace.github.io/RenewalMgtApp-Html/app/guest_profile.html

Please help to clarify it.

**Comment by d33pspace** [comment]
1. I believe this is correct, @MariiaBubley please confirm.
2. Your understanding here is not quite right. I think the graphic below should explain. 
     a. Tapping on someone in the In-Service list begins the service process (if an open laundry tag exists, the Return page is opened, or if an open laundry tag does not exist, the Give page is opened).
     b. If there is a vacancy in the In-Service list, tapping on the person highlighted in the Waiting list moves them to the In-Service list. 
     c. Tapping on non-highlighted Guests in the Waiting list OR anyone in the Finished list, opens the Guest profile.
![Screenshot 2021-09-10 101818](https://user-images.githubusercontent.com/13606352/132788608-7be81c38-0e59-436c-818f-dddb979f6375.png)

**Comment by MariiaBubley** [comment]
@edwazhao 1. This is correct, 2. Is this case is clear now?

**Comment by edwazhao** [comment]
Hi @d33pspace , @MariiaBubley , yes, these helps with main page, but actually I was asking the behavior of **Guest List**
Normally we tap a guest line in Guest List, will open Guest Profile page, right?
My questions are following:
1. How to add a guest to the waiting list? is it by tapping a guest line in Guest List?
2. How to open edit guest profile page? Do we have the edit button in view Guest Profile page?

Jimmy, your comment reminds me that, we may need an animation for moving a guest from waiting list to in-service list, which would need HTML designer's help.

**Comment by d33pspace** [comment]
@edwazhao Ah. I see... 

(2) Concerning editing the Guest profile, I see "Edit" in the upper right-hand corner of guest_profile.html. Does this answer this question?

Aha! You are asking about the process of adding a Guest to the Waiting List on the main page. I also need to clarify with Mariia...

@MariiaBubley 

(1) On the Main page, the User taps the FAB to search for a Guest to add to the Waiting List. According to the User Flow, they would tap on the Guest Line to open the Guest Page, or tap on Start to add them to the Waiting List. I don't see Start. Can you point it out please?

(3) Edward originally asked about the difference of tapping on FAB on Main Page and selecting Guest List from the menu. My understanding is tapping FAB begins the process for adding a Guest to the Waiting List. Selecting Guest List from the menu will also bring up the Guest List, but this list will not have Start for quickly adding the Guest to the Waiting List. Do I understand correctly?

(4) What do you think of Edward's suggestion of an animation for moving a Guest from the Waiting List to the In Service list?

**Comment by edwazhao** [comment]
Thanks Jimmy, now I see the Edit button on Guest Profile.

**Comment by MariiaBubley** [comment]
@edwazhao @d33pspace 
1) Look at the image, are we can make zones on the Guest line?
![image](https://user-images.githubusercontent.com/89512026/133373221-359744c8-d15d-4ee7-af1b-2edb82d96fdf.png)
3) It sounds logical. It means that now we have two Guestlist pages 1-From FAB, 2-from Sidebar. I propose to change the 2nd title to "Start the service", 1st leave Guest List.  Also, I have already removed the Start buttons from the Guestlist Page. 
4)If you mean Drag&Drop animation, I can prepare the example.

**Comment by d33pspace** [comment]
@AnKar112 @academws The arrows on the right side of Guest List have been removed (in Figma see Guest List - Guest Account > Guest list). Then another page has been created called "Start the Service" (in Figma see Main page > Guest list) which is similar to the original Guest List. Can you please make updates to the HTML templates accordingly?

**Comment by AnKar112** [comment]
Done. I found one difference - new page have this http://ipic.su/img/img7/fs/kiss_27kb.1631746227.png and old one have no. Is it a mistake?

**Comment by d33pspace** [comment]
@AnKar112 @academws I'm sorry I don't see the two files in the repository, can you point them out, please?

@MariiaBubley Can you please reply to the question directly above regarding the difference between the two files in the Figma models?

**Comment by AnKar112** [comment]
Pushed just now. Check again, please

**Comment by d33pspace** [comment]
@AnKar112 Thank you! I will check all again. No need to comment again on all issues.

**Comment by d33pspace** [comment]
@AnKar112 @academws 
- Guest List looks good!
- For Start the Service, can you please link to two different pages (any pages) to demonstrate the click/tap zones as indicated here?

![133374084-879f52b0-2ad9-4fc3-9f0d-b1519217e5dc](https://user-images.githubusercontent.com/13606352/133524716-953a387a-b13c-440f-af50-f28e56a5e68b.png)

@MariiaBubley Can you please reply to Anton's question above regarding the difference between the two files in the Figma models?

Guest List: https://d33pspace.github.io/RenewalMgtApp-Html/app/guest_list.html
Start the Service: https://d33pspace.github.io/RenewalMgtApp-Html/app/start_the_service.html

**Comment by MariiaBubley** [comment]
@AnKar112 @d33pspace 

All pages with a list or catalogue have search lines and sort icons (these icons switch between each other) - by name and by date.
![image](https://user-images.githubusercontent.com/89512026/133563397-ac269c26-602e-4abe-9053-f592adb988ae.png)

**Comment by d33pspace** [comment]
@AnKar112 @academws Please make the sort icon in the upper right toggle between name and date when clicked/tapped.

**Comment by AnKar112** [comment]
Could you specify, what pages should contain this? For example, this page have search, but have no this icon http://ipic.su/img/img7/fs/kiss_22kb.1631826264.png

**Comment by d33pspace** [comment]
@MariiaBubley 
(1) Anton has updated the sort icon in Guest list and Start service page.
https://d33pspace.github.io/RenewalMgtApp-Html/app/guest_list.html
https://d33pspace.github.io/RenewalMgtApp-Html/app/start_the_service.html

(2) I agree it should be added to User list, but note it is not present in the Figma model.

(3) The sort icon is also not on Item catalogue in the Figma models, but it does have search. I actually don't think search/sort is necessary here. Items are organized under Types and there are not too many. Users will be used to finding them using the other pages.

**Comment by d33pspace** [comment]
@AnKar112 @academws 

(1) Please add the sort icons to user_list. I realize it's not in the Figma model, but it should be. We apologize.
(2) Please remove the search bar from item_catalogue. Again, this is our mistake. Then please unify the header for this page as described in #24

**Comment by MariiaBubley** [comment]
@d33pspace 
2) I think the item catalogue also should have a search bar and sort, it can be useful for users. 

@AnKar112 @academws 
Excuse me for the inconsistencies in Figma, some cases I make during development, so sometimes appear mistakes.

**Comment by d33pspace** [comment]
@MariiaBubley Thanks for this good idea, I don't mean to imply it was a mistake originally. But I'd prefer we leave out search and sort for clothing items. I would prefer the Types be in logical order. This will be one of the most common things Users do, so they will learn where clothing is quickly.

@AnKar112 @academws 
Please proceed with (1) and (2) above.

**Comment by MariiaBubley** [comment]
@d33pspace ok, I have already changed it on the Figma guide

**Comment by d33pspace** [comment]
@AnKar112 @academws 
- Please add the sort icons to user_list like you did on guest_list and start_the_service. This is not in Figma but it should be.

**Comment by AnKar112** [comment]
Done. Btw, in item catalogue this title have 500 font-weight http://ipic.su/img/img7/fs/kiss_9kb.1632058721.png
and in guest list 700. Maybe it should be simular?

**Comment by d33pspace** [comment]
@MariiaBubley Can you please check the header font weights as suggested by Anton above and tell us if there are any pages that are incorrect and how to correct them?

**Comment by MariiaBubley** [comment]
@d33pspace @AnKar112 all such titles on all pages have to be the same: 10 px, weights 500, Grey-2
