### ISSUE TITLE
Security advisories

### ISSUE THREAD

**Issue by d33pspace** [d33pspace/RenewalMgtApp-Html#25]
Hi there! Please check out these security vulnerabilities when possible...
![Screenshot 2021-09-14 101638](https://user-images.githubusercontent.com/13606352/133183618-15c3d9d7-12ed-42af-b49c-bc64f5190b69.png)

**Comment by edwazhao** [comment]
Hi @d33pspace , seems I don't have this view
![image](https://user-images.githubusercontent.com/11383105/133215451-e118411c-3021-4609-ad2b-fe2444de4567.png)

**Comment by d33pspace** [comment]
I believe it is @AnKar112 @academws that should make this update? Here is the full information...

![Screenshot 2021-09-14 184853](https://user-images.githubusercontent.com/13606352/133244735-6654b8d7-9c75-41ca-8027-48bcfa3898ec.png)
![Screenshot 2021-09-14 184913](https://user-images.githubusercontent.com/13606352/133244742-77e36f36-ca14-48fc-9d62-79ee7fe3c0bc.png)
![Screenshot 2021-09-14 184930](https://user-images.githubusercontent.com/13606352/133244743-a7453a92-4a5a-47ea-a483-4ef8e565abb4.png)
![Screenshot 2021-09-14 184951](https://user-images.githubusercontent.com/13606352/133244745-22f9649a-4c49-42c0-899d-94d77d147fb3.png)

**Comment by AnKar112** [comment]
This happens because of package-lock.json file. You don't need it anyway, so I add it to ignore list.
