### ISSUE TITLE
Start Service page

### ISSUE THREAD

**Issue by d33pspace** [d33pspace/RenewalMgtApp-Html#26]
@AnKar112 @academws 
- Please change the title in the header from "Start the service" to "Start service"
- There are two fields for clicking/tapping on each line, the main line (left) should open guest_profile, the arrow (right) should open main_page. Can you demonstrate this please, and also please mind the click/tap fields should be square.
![Screenshot 2021-09-17 095510](https://user-images.githubusercontent.com/13606352/133711528-b4234d7c-8361-49e1-84d3-fc8f9567b58e.png)

**Comment by AnKar112** [comment]
Done
