### ISSUE TITLE
Give page - modal

### ISSUE THREAD

**Issue by d33pspace** [d33pspace/RenewalMgtApp-Html#28]
@MariiaBubley 
In my understanding, the distribution history modal on the give page should only open when a number to the right of a Type is tapped. Because some (actually most) lines will not have any relevant distribution history to share. Plus, the distribution history is only relevant to Types, not Items.

https://d33pspace.github.io/RenewalMgtApp-Html/app/give_page.html

So I think: 
- Tap on whole line of Types that contain Items == Expand/collapse Items.
- Tap on [+] == add to Giving list.
- Tap on number == open distribution history modal.
 
Or for lines that are not Types that contain Items, we could make the tap whole line == add to Giving list.

What do you think?

**Comment by MariiaBubley** [comment]
@d33pspace How about nest flow?

![image](https://user-images.githubusercontent.com/89512026/133985157-faedfa3f-3cf2-480d-8140-38922ee0bc6c.png)

**Comment by d33pspace** [comment]
How about this?

The reason I think it makes more sense is when the modal is opened, it contains all Items of that Type.

![Screenshot 2021-09-21 091504](https://user-images.githubusercontent.com/13606352/134098017-91d0f8e1-d47e-423f-8011-838527847499.png)

**Comment by MariiaBubley** [comment]
@d33pspace Do you mean, that the modal include all items of this type? 

I thought before in the modal window, there is only one item but all repetitions
