### ISSUE TITLE
Plus sign on ratings unnecessary

### ISSUE THREAD

**Issue by d33pspace** [d33pspace/RenewalMgtApp-Html#29]
@MariiaBubley 
I don't think the [+] sign before the smile/frown face on these pages is necessary. It's a little confusing to me.

What do you think?

https://d33pspace.github.io/RenewalMgtApp-Html/app/guest_profile_behavior.html
https://d33pspace.github.io/RenewalMgtApp-Html/app/reports_behavior_overview.html

**Comment by MariiaBubley** [comment]
@d33pspace yes, you're right.

**Comment by d33pspace** [comment]
@AnKar112 @academws 
Please remove the little plus signs to the right of the faces on guest_profile_behavior and reports_behavior_overview.

![Screenshot 2021-09-17 151704](https://user-images.githubusercontent.com/13606352/133740995-c381026b-b12b-43c2-9814-5209d29cbfa4.png)

**Comment by AnKar112** [comment]
Done
