### ISSUE TITLE
forgot_password error message not in red and button name is not correct

### ISSUE THREAD

**Issue by edwazhao** [d33pspace/RenewalMgtApp-Html#3]
https://d33pspace.github.io/RenewalMgtApp-Html/app/forgot_password.html

![image](https://user-images.githubusercontent.com/11383105/132149861-2c261de6-d17d-41ed-afdf-f9f4d4ae07f7.png)

**Comment by d33pspace** [comment]
@edwazhao Can you check to see if this has been done. I don't believe I can test myself on the templates. If it has not been done I will remind them today.

**Comment by edwazhao** [comment]
thank you for fixing it.
