### ISSUE TITLE
Guest Profile

### ISSUE THREAD

**Issue by d33pspace** [d33pspace/RenewalMgtApp-Html#32]
@AnKar112 @academws 

https://d33pspace.github.io/RenewalMgtApp-Html/app/guest_profile.html
- This toggle on the Guest Profile needs to change according to the list that the Guest is currently in. The default state is no list active. And only one list can be active at a time. Can you please demonstrate?
![Screenshot 2021-09-17 145326](https://user-images.githubusercontent.com/13606352/133737961-81bd5b83-4f06-4fc2-bf6e-0a22206dd7ce.png)

- Also my mistake ... the phone number and ID number on guest_profile are real. Can you please replace them with placeholders of the same length? And can we purge old versions of this page from the repository (because it's public)?

**Comment by AnKar112** [comment]
Sorry, I didn't get first task. We have design for content in tabs?

**Comment by d33pspace** [comment]
@AnKar112 @academws 
Hello!

These are actually not tabs, they are buttons. In the graphic above, the Guest is currently in the In-Service list. But the User could tap "Waiting" or "Finished" to move her to that list. The only thing that happens in the UI is the active button moves to the tapped list. The default button is no button is active. And the buttons can also be disabled. 

Can you please demonstrate like this:

- Initial state: No buttons active, In-Service button disabled.
- User can tap on Waiting or Finished buttons to activate.

**Comment by AnKar112** [comment]
Get it. Done. check please
