### ISSUE TITLE
Main page - FAB

### ISSUE THREAD

**Issue by d33pspace** [d33pspace/RenewalMgtApp-Html#33]
@MariiaBubley 
The FAB on the Main page is for adding Guests to the Waiting list. It seems like a plus sign with the people would be helpful. What do you think?

**Comment by MariiaBubley** [comment]
@d33pspace 
Do you mean this icon?

![image](https://user-images.githubusercontent.com/89512026/133755792-1d98da73-e46b-42e4-b015-631ccf5c85ff.png)

**Comment by d33pspace** [comment]
Yes! Perfect. Sorry I may not have noticed this in Figma. The icon in the HTML models is incorrect. I'll have Anton fix it.
