### ISSUE TITLE
Reports - column header icons

### ISSUE THREAD

**Issue by d33pspace** [d33pspace/RenewalMgtApp-Html#34]
@MariiaBubley 
The icons that are the column headers on the operations report are very small and it's hard to tell the purpose. Do you think abbreviated text would be more practical? 

https://d33pspace.github.io/RenewalMgtApp-Html/app/reports_operations.html

**Comment by d33pspace** [comment]
@MariiaBubley 
I like this! But it's the icons for the column headers I think can be difficult to understand.
![Screenshot 2021-09-18 090228](https://user-images.githubusercontent.com/13606352/133866957-f4fe76f6-8cef-4ff2-91b2-e60dd98ab908.png)

Can we do: 
GIVEN     LOST     UNFULFILLED     TRASHED

Or if we need them even shorter:
GIVEN     LOST    UNFL'D     TRASH

**Comment by MariiaBubley** [comment]
How about such titles:
![image](https://user-images.githubusercontent.com/89512026/133981204-3e91035f-ed91-4a67-8b47-8ae5192fbb3e.png)

But I can not make them longer.

**Comment by MariiaBubley** [comment]
And we also have to change other titles on the same
Cange:
Laundry - Wash
Requests - Needs

**Comment by MariiaBubley** [comment]
done
https://www.figma.com/file/3DZItCETG2QIvRYnlQvMyn/Renewal-Mobile-App?node-id=1783%3A45773
