### ISSUE TITLE
Reports - date picker

### ISSUE THREAD

**Issue by d33pspace** [d33pspace/RenewalMgtApp-Html#35]
@AnKar112 @academws 
The date can be changed on all reports such as:
https://d33pspace.github.io/RenewalMgtApp-Html/app/reports_behavior.html

Figma:
![Screenshot 2021-09-18 083837](https://user-images.githubusercontent.com/13606352/133866108-9e841797-8b8c-41fd-acee-ad5f2cac1545.png)

Can you please demonstrate this UI function?

**Comment by AnKar112** [comment]
Have a little problems here. Add class active to overlay and you will see datepicker http://ipic.su/img/img7/fs/kiss_94kb.1632085258.png
This is simple jQuery datepicker. And it couldn't pick a range of dates. I thought that you (or your developer) have some datepicker plugin that I should use for this project.

**Comment by d33pspace** [comment]
@edwazhao See Anton's comment above. We need a date picker that can select a range of dates. Do you have a suggestion?

**Comment by edwazhao** [comment]
Hi @d33pspace , I would like to choose [https://vcalendar.io/datepicker.html#date-ranges](https://vcalendar.io/datepicker.html#date-ranges) or [https://vue3datepicker.com/api/props/#range](https://vue3datepicker.com/api/props/#range)
But I am OK if Anton cannot use my suggestion above, he can choose what the convenient for the HTML version, I will replace later.

**Comment by d33pspace** [comment]
@AnKar112 @academws 

If you can please just demonstrate modal window opens with any calendar when the users taps the date range link that is enough. You do not need to demonstrate date-range selection functionality.

**Comment by AnKar112** [comment]
As demonstration: reports_behavior.html
If it's enought, I will add it to other report pages. If you need something **edwazhao** proposed, I can do it, but need some time to install and style this datepicker.

**Comment by d33pspace** [comment]
Thank you, @AnKar112 @academws 

I spoke with the back-end developer and he says if it's possible for you to install and style V-Calendar that would be ideal. 
https://vcalendar.io/datepicker.html#date-ranges

**Comment by AnKar112** [comment]
as I understand, this is mistake? https://s.micp.ru/pXRr7.png

**Comment by AnKar112** [comment]
I'm done, but this calendar have no a lot of possibles to style it. 
Take a look - is it ok for you? It looking different to design, but this is the best I can make with V-Calendar.

**Comment by d33pspace** [comment]
@MariiaBubley 
The date picker style options are limited. Anton has done his best. Can you check out the look on... 
https://d33pspace.github.io/RenewalMgtApp-Html/app/reports_behavior.html
I think it looks great! My only recommendation if it's possible would be that all selected dates are white instead of combination of white and black.
![Screenshot 2021-09-23 091311](https://user-images.githubusercontent.com/13606352/134441682-cd081fcf-a221-4de0-bbcb-545ddf2f954b.png)

**Comment by d33pspace** [comment]
@AnKar112 @AnKar112 
Is it possible that all of the selected dates are white numbers instead of both white and black numbers?

**Comment by MariiaBubley** [comment]
@d33pspace @AnKar112 
Please fix the margins and paddings, date colours on highlighted line, border-radius of the highlighted line. 
I made visualisation here https://www.figma.com/file/3DZItCETG2QIvRYnlQvMyn/Renewal-Mobile-App?node-id=148%3A998

![image](https://user-images.githubusercontent.com/89512026/134642738-89e24210-14d4-43eb-8d30-75f68a59452d.png)

**Comment by d33pspace** [comment]
@AnKar112 @academws 
I realize your styling options with V-Calendar are limited. Is there any of this you can accommodate? I think minimally all white numbers for selection would be nice.

**Comment by AnKar112** [comment]
Sorry, I literally can't handle anything what you asking for.
