### ISSUE TITLE
Return page

### ISSUE THREAD

**Issue by d33pspace** [d33pspace/RenewalMgtApp-Html#36]
@AnKar112 @academws 
I believe the FAB on the Return page should close when the X at the bottom is tapped?
https://d33pspace.github.io/RenewalMgtApp-Html/app/return_page.html

Also, the FAB should appear only when all items have been "handled" - this means all items have been either marked with a check, trash, or lost. And when the FAB appears, and then later one of the items is unmarked, the FAB would disappear. Can you demonstrate please?

**Comment by AnKar112** [comment]
Shoult tap on trash\lost check checkbox?

**Comment by d33pspace** [comment]
@AnKar112 @academws 
Hi.
- This is correct, all items checked, FAB menu is active:
![correct](https://user-images.githubusercontent.com/13606352/133961929-edf331d5-761a-44e4-9df5-93f34e3bb7e8.png)

- But if one item is unchecked, FAB menu should disappear.
- So for example, this is incorrect. FAB menu should not be here:
![FAB should disappear](https://user-images.githubusercontent.com/13606352/133962059-8cf27182-3b05-4521-b6b0-95fae92b17df.png)

- This is also correct, all items are either checked, or marked as Trash or Lost:
![FAB should appear](https://user-images.githubusercontent.com/13606352/133962021-622bbe42-8a80-4c7f-89a2-b9a6d0ca8d15.png)

- But again, if one item is not handled, FAB should disappear. 
- For example, this is incorrect. FAB menu should not be here because "PANTS | Jeans" line is not handled.
![FAB should also disappear](https://user-images.githubusercontent.com/13606352/133962183-c1b607a7-9da3-4f00-aefb-74bb75475c6f.png)

- On each line, only one can be active: checkbox, trash and lost. So this is impossible:
![impossible](https://user-images.githubusercontent.com/13606352/133961878-4efab17f-5e38-4c45-b781-8f9b7895e69b.png)
t.

**Comment by AnKar112** [comment]
Done. check it please
