### ISSUE TITLE
Unify dropdown menus

### ISSUE THREAD

**Issue by d33pspace** [d33pspace/RenewalMgtApp-Html#38]
@AnKar112 @academws 

- On the new_item, edit_guest, and new_guest pages, when one menu is opened, please close all other dropdown menus.
- Please implement the animated flip effect on the expand/collapse arrow on new_item and new_guest like is on edit_guest.

https://d33pspace.github.io/RenewalMgtApp-Html/app/new_item.html
https://d33pspace.github.io/RenewalMgtApp-Html/app/new_guest.html
https://d33pspace.github.io/RenewalMgtApp-Html/app/edit_guest.html

**Comment by AnKar112** [comment]
Done
