### ISSUE TITLE
new item page with many item types, not user-friendly

### ISSUE THREAD

**Issue by edwazhao** [d33pspace/RenewalMgtApp-Html#4]
When there are more than 10 item types in the dropdown list which is true to our system, the page's height changed a lot, is it reasonable to make a scrollbar for the dropdown list like red marked in the picture?

![image](https://user-images.githubusercontent.com/11383105/132151485-4ab9df4b-3f5e-4e27-ba1c-de38a2b17c7b.png)

**Comment by MariiaBubley** [comment]
Hello, @edwazhao 
yes, sure! I even made relevant components in Figma, with search and without: 
![image](https://user-images.githubusercontent.com/89512026/132242253-e51c24ec-063b-48fc-b51c-2b986d0725c2.png)

**Comment by d33pspace** [comment]
@academws Please update the HTML templates accordingly.

**Comment by edwazhao** [comment]
Hi @MariiaBubley , thank you for the changes, it looks nice.

**Comment by d33pspace** [comment]
@edwazhao I do not see in our HTML templates which one I can test to see if this work has been done. Can you provide a link please?

**Comment by d33pspace** [comment]
@MariiaBubley Question from FD: This function is needed only a new item page or something else?

**Comment by edwazhao** [comment]
@d33pspace , yes, please check https://d33pspace.github.io/RenewalMgtApp-Html/app/new_item.html
From my point of view the style should apply for all dropdown list.

@academws , thank you for adapting it, still a minor issue, if we click Distribution Policy first, and then click Item Type, the Item Type will be covered.
![image](https://user-images.githubusercontent.com/11383105/132658507-5fea7868-9442-4f26-baae-92b4025b4379.png)

**Comment by d33pspace** [comment]
@academws As Edward points out above, on this page if you click on Distribution Policy then click on Item Type, the Item Type is hidden.

**Comment by d33pspace** [comment]
@edwazhao This is fixed. Can you confirm everything is to your liking?

**Comment by d33pspace** [comment]
@AnKar112 @academws This looks good but my preference would be that when one dropdown list opens, the other closes automatically. Is this possible?

**Comment by edwazhao** [comment]
Thanks, I will close it.
