### ISSUE TITLE
Navigation, FAB

### ISSUE THREAD

**Issue by d33pspace** [d33pspace/RenewalMgtApp-Html#40]
@MariiaBubley 
I have taken a different path than is in the user flow...

When there is an open spot in the In-Service list, when the User taps on a Guest in the Waiting list, I would like the first action to be for the Guest to move to the In-Service list. Because sometimes the User will call for a Guest, but it may take them a few minutes to come to the desk, so they may actually do something else before they begin assisting that Guest.

Then when a Guest is tapped on in the In-Service list...

(a) If the Guest has an active laundry tag, the Return page is opened.
(b) If the Guest does not have an active laundry tag and the In-Service timer is < 10 minutes, the Give page is opened.
(c) If the Guest does not have an active laundry tag and the In-Service timer is > 10 minutes, the Take page is opened.

Also, I'm not sure that it is clear from the User flow when the In-Service timer stops and the Guest is moved to the finished list. My proposal is either of these two scenarios:

(a) The User adds the first Item to the Laundry list on the Take page.
(b) The User selects a Finish service icon in the FAB.

By the way, when a Guest is in the In-Service list, how goes the User open the Guest page?

Further, on the FAB...

(1) I believe there is no reason for the FAB to have a "return laundry" icon at all. The User must go to the Return page upon initiating service, and the FAB does not appear until all items are handled. Then, once the User leaves the Return page, there is no reason to go back there. Do you agree?

(2) I believe the take page doesn't need a take icon in the FAB and the give page doesn't need a give icon in the FAB. Do you agree?

![image_2021_09_22T01_47_03_317Z](https://user-images.githubusercontent.com/13606352/134274757-22f55872-2992-44ee-9e3d-9689696f61a2.png)

**Comment by MariiaBubley** [comment]
@d33pspace 
I have drawn a new flow using (b) scenario:
https://miro.com/welcomeonboard/bHlUOTNiUk9TVE1pTEJDS2o1aWIyQ3hOOE5BU0dla2FoTTZTa1ExVmZMdkdPemJBR0VIbWl5bTd2VDlwM3NBbHwzMDc0NDU3MzQ4NDk0NjExNDcx?invite_link_id=960248202456

_By the way, when a Guest is in the In-Service list, how goes the User open the Guest page?_
- or by tapping on the avatar (inside all Main Page lists) 
- or through the sidebar - guests list - guest page

Further, on the FAB, you are right and I have illustrated your thoughts. 
https://www.figma.com/file/3DZItCETG2QIvRYnlQvMyn/Renewal-Mobile-App?node-id=1878%3A43804

**Comment by d33pspace** [comment]
@MariiaBubley 
New flow looks great! Thank you!

A few more thoughts on FAB...

(1) What do you think about Guest page button in FAB? This way if a User is on Return, Give or Take pages, they can quickly open the Guest page and give the Guest a rating. In my opinion, this will be the time the User will instinctively want to give a rating.

(2) What do you think about Service Finished button in FAB? If a Guest leaves at any point, they can be moved to the Finished list easily.

(3) I think the Meal button in FAB may be superfluous. The meal service will mainly be managed through the Main Page and that is sufficient. I recommend removing it from FAB.

So I propose the following FAB scenarios for each page:

Return page (note different order here, I think Give Clothes should come before Take Laundry.)
- Send to shower
- Give clothes
- Take laundry
- Stop service
- Guest page
- Home

Take page:
- Send to shower
- Give clothes
- Stop service
- Guest page
- Home

Give page:
- Send to shower
- Take laundry
- Step service
- Guest page
- Home

**Comment by MariiaBubley** [comment]
@d33pspace yes, your thoughts make sense, so I made the changes to mockups
https://www.figma.com/file/3DZItCETG2QIvRYnlQvMyn/Renewal-Mobile-App?node-id=1878%3A43804

**Comment by d33pspace** [comment]
@AnKar112 @academws 
Please update the FAB on the Return page, Take page and Give page as shown here:
https://www.figma.com/file/3DZItCETG2QIvRYnlQvMyn/Renewal-Mobile-App?node-id=1878%3A43804

**Comment by AnKar112** [comment]
only icons changed, right? done

**Comment by d33pspace** [comment]
@AnKar112 @academws 
Almost perfect... 😊

On the Give page, please change the second icon (pointed out below) to the soiled t-shirt icon.
![Screenshot 2021-09-29 093052](https://user-images.githubusercontent.com/13606352/135187740-c4cb4e95-ba86-47b1-b53a-2f2ab7fd54e3.png)

**Comment by AnKar112** [comment]
Done
