### ISSUE TITLE
User Admin Guest Pages

### ISSUE THREAD

**Issue by MariiaBubley** [d33pspace/RenewalMgtApp-Html#41]
@AnKar112  @d33pspace Please, edit these pages. I added email on all User Pages and unify the paddings

https://www.figma.com/file/3DZItCETG2QIvRYnlQvMyn/Renewal-Mobile-App?node-id=1878%3A42755

**Comment by AnKar112** [comment]
Edit user profile - how this page called? Couldnt find it here https://d33pspace.github.io/RenewalMgtApp-Html/app/
And can you clarify where exactly should I looking about paddings and what the different?

**Comment by d33pspace** [comment]
@MariiaBubley 
This is done. But we're not sure what you mean about "unify the paddings." In my opinion, headers and padding is looking good across all pages now. 😊

**Comment by MariiaBubley** [comment]
Yes, now they are fine
But I found new edit on the Account page  - Role input is doubled & delete my profile has different padding.
https://d33pspace.github.io/RenewalMgtApp-Html/app/edit_user_profile.html

**Comment by d33pspace** [comment]
@AnKar112 @academws 
(1) Please delete the first Role input (the one that is not the dropdown).
(2) Please correct the padding on the left of the "Delete my profile" link.

**Comment by AnKar112** [comment]
Done
