### ISSUE TITLE
Unify Give and Take pages

### ISSUE THREAD

**Issue by d33pspace** [d33pspace/RenewalMgtApp-Html#42]
@AnKar112 @academws 
I need to explain something important that both the Give and Take page share... (Thank you very much for your patience!)

The Give page has the Giving list at the top. This is the list of items we are giving Guests.
The Take page has the Laundry list at the top. This is the list of items we will take from our Guests to wash and return later.

Both of these pages have a Most Commonly Used list for items frequently used.
Both of these pages also have the full Clothing List to browse all clothing items.

There are two types of items. (1) Items with sub-items, and (2) Items without sub-items.

Items with sub-items look like this in the Most Commonly Used list:
![Screenshot 2021-09-23 153752](https://user-images.githubusercontent.com/13606352/134470898-a48837e3-9616-41c4-98ed-62eb82edda1d.png)
The item here is "Pants" the sub-item is "Jeans"

Items without sub-items look like this in the Most Commonly Used list:
![Screenshot 2021-09-23 153809](https://user-images.githubusercontent.com/13606352/134470984-1268f93c-060b-4430-9489-6f9ea683e70c.png)
The items here is "Socks". There is no sub-item. (We only have one kind of socks.)

As you know, in the full Clothing List, if an item has sub-items, it expands. The User can then add these sub-items to the Giving list or Laundry list. 

And in the full Clothing List, if an item does not have sub-items, it does not expand. The User can directly add these items to the Giving list.

The thing I want to tell you is that in the Giving list (on the Giving page) and on the Laundry list (on the Take page), the items need to be in the same format they are in the Most Commonly Used list. 

I think this should be easy for moving items from the Most Commonly Used list, OR from items without sub-items from the Clothing List. However, if an item with sub-items is expanded in the Clothing List, it needs to change formats when it is added to the Giving list or Laundry list. It needs to appear in this format:

![Screenshot 2021-09-23 153752](https://user-images.githubusercontent.com/13606352/134470898-a48837e3-9616-41c4-98ed-62eb82edda1d.png)

So, for example, if the item "Pants" is expanded in the full Clothing List, and it reveals the sub-items "Jeans", "Sweat pants" and "Dress pants", then the User adds "Jeans" to the Giving list or Laundry list, it needs to be in the format:
![Screenshot 2021-09-23 153752](https://user-images.githubusercontent.com/13606352/134470898-a48837e3-9616-41c4-98ed-62eb82edda1d.png)
when added to the Giving list or Laundry list.

Of course things that would happen on the back-end you do not need to demonstrate, but if you can please demonstrate the UI functionality of this it would be very helpful!

**Comment by AnKar112** [comment]
Not a problem, but this pages have this logic: 
- all cards in laundry\giving list already exist on the page, just disabled. When you click on plus, it enable card https://s.micp.ru/25y6t.png
Card can have any layout, but you need to say, which card should have which type of layout. Because t-shirt, for example, on take page, have (2) type on layout in MOST COMMONLY USED and (1) type of layout in FULL CLOTHING LIST

**Comment by d33pspace** [comment]
@AnKar112 @academws 
I am consolidating issues #9 (Give page) and #27 (Take page) here.
Note while these pages are similar, there are some key differences.

Both pages:
(1) The counters that appear next to some items only appear in the Most Commonly Used list and the Full Clothing List of the Give page. They do not appear in the Giving List of the Give page, and they do not appear anywhere on the Take page. So as of right now, (a) they need to be added to the Most Commonly Used list on the Give page (but not to all items in the list). And (b) they need to be removed from both the Giving List on the Give page and the Laundry List on the Take page. When multiple items are added to these lists, multiple rows appear. I'm sorry if this requires a lot of re-work, but it is necessary and I'm of course happy to pay for it. This is my own fault. I only realized this as you have been putting these HTML templates together. 
(2) In both the Giving List on the Give page and the Laundry List on the Take page, please demonstrate an item being added which has a sub-item as I described above in this thread. 

In other words, please demonstrate both of these styles in the Giving List on the Give page and the Laundry List on the Laundry page. You of course do not need to demonstrate anything that would require back-end logic.
![Screenshot 2021-09-23 153752](https://user-images.githubusercontent.com/13606352/134470898-a48837e3-9616-41c4-98ed-62eb82edda1d.png)
![Screenshot 2021-09-23 153809](https://user-images.githubusercontent.com/13606352/134470984-1268f93c-060b-4430-9489-6f9ea683e70c.png)

Take page:
(3) The Laundry list background needs a light grey shading.
(4) Please demonstrate: (a) Add a sub-item from the Full Clothing List to the Laundry List. (b) Add an item without sub-items to the Laundry list. (Right now there are no items without sub-items in the Full Clothing List. I suggest instead of giving Shorts sub-items, you remove the arrow and replace it with a [+] then allow it to be added directly to the Laundry List.)

Give page:
(5) I believe during a recent fix there appeared another small problem... when an item is added to the Giving List, the header is incorrect (it says "Laundry List") and the columns are not correct. The Giving List does not have a Trash column, it has a "Not Found" column. Also, the icons do not work.
![Screenshot 2021-09-24 081822](https://user-images.githubusercontent.com/13606352/134600160-426721f6-4460-4420-a6ea-0fb2b12da326.png)
.

**Comment by AnKar112** [comment]
Please, check it now. So many information - I can miss something

**Comment by d33pspace** [comment]
@AnKar112 @academws 
Really great work, Anton, thank you!

There remain only a few tiny things now:

(1) On both pages, the click field around the [-] in the RMV column is not square. 
(2) On the Take page, the click field around the [+] in the Pants row in the Full Clothing List (the item without sub-items) is not square. (See screenshot here.)
![Screenshot 2021-09-28 133815](https://user-images.githubusercontent.com/13606352/135029642-93c9a3cc-5645-4932-95dd-138a3bbc99d2.png)
(3) On the Give page, the [+] in the Shorts row in the Full Clothing List (the item without sub-items) is off centered and the click field is not square. (See screenshot here.)
![Screenshot 2021-09-28 133447](https://user-images.githubusercontent.com/13606352/135029430-1877d0fc-35a5-4f68-8882-3c9ee1705c23.png)
(4) On the Give page please change "Clothing List" to "Full Clothing List".

**Comment by AnKar112** [comment]
Everything is done

**Comment by d33pspace** [comment]
@AnKar112 @academws 
Almost there! 😍

(1) On the Take page, the click field around the [+] in the Pants row in the Full Clothing List (the item without sub-items) is still not square. 
![Screenshot 2021-09-28 133815](https://user-images.githubusercontent.com/13606352/135029642-93c9a3cc-5645-4932-95dd-138a3bbc99d2.png)

(2) On the the Give page, first add Shorts from the Full Clothing List (the item without sub-items) to the Giving list. Neither the Not Found icon or the Rmv [-] is functional until another item is added. The same is true on the Take page when adding Pants from the Full Clothing List.

**Comment by AnKar112** [comment]
Fixed, check please
