### ISSUE TITLE
Edit Item: dropdown is not displayed completely 

### ISSUE THREAD

**Issue by edwazhao** [d33pspace/RenewalMgtApp-Html#47]
https://d33pspace.github.io/RenewalMgtApp-Html/app/edit_item.html

See screenshot below, 7 days option is not displayed. 

 
![image](https://user-images.githubusercontent.com/11383105/138116561-786cecf8-ca4c-4f36-81f1-ca03e97b3d94.png)

**Comment by d33pspace** [comment]
@AnKar112 @academws 
Please take a look at this when you can. Thank you!
