### ISSUE TITLE
Edit Guest: scrollbar for Province dropdown

### ISSUE THREAD

**Issue by edwazhao** [d33pspace/RenewalMgtApp-Html#48]
https://d33pspace.github.io/RenewalMgtApp-Html/app/edit_guest.html

1. There is no confirm button avaiable, please help to add it.
2. Please add scrollbar for Province dropdown

![image](https://user-images.githubusercontent.com/11383105/138297956-31377dcf-9024-455a-822f-f75420e0ef16.png)

**Comment by AnKar112** [comment]
1 - Done. Should I do the same for New Guest page?
2 - Should it be with search as in New Item?
And, by the way, should I do the same logic for New Item page, as I do just now for Edit Guest (in Edit Guest button appear on input, and when all inputs are empty and no dropdown chosen, it dissepear. In New Item more simple logic - it just appear on blur and couldn't be disappear.

**Comment by edwazhao** [comment]
Thanks @AnKar112 .
