### ISSUE TITLE
all distribution list in give page is not scrollable

### ISSUE THREAD

**Issue by edwazhao** [d33pspace/RenewalMgtApp-Html#49]
https://d33pspace.github.io/RenewalMgtApp-Html/app/give_page.html

1. If there are a lot records, there is no scrollbar
2. If there are only few records, there are too much white space at bottom.

![image](https://user-images.githubusercontent.com/11383105/140374631-2b427d60-345c-4418-8b09-5c042066d030.png)

**Comment by d33pspace** [comment]
@AnKar112 @academws Please take a look. Thank you!

**Comment by AnKar112** [comment]
Done

**Comment by edwazhao** [comment]
Thank you for the fix.
