### ISSUE TITLE
Item Catalogue

### ISSUE THREAD

**Issue by d33pspace** [d33pspace/RenewalMgtApp-Html#5]
How do you open the Edit Item page from the Item Catalogue?

![Screenshot 2021-09-06 130945](https://user-images.githubusercontent.com/13606352/132163670-fe6ffe39-b645-4908-8a96-991a3ea5fa16.png)

**Comment by MariiaBubley** [comment]
when user taps on item line 
![image](https://user-images.githubusercontent.com/89512026/132242466-944e1d08-f09d-496c-928d-ddee6dde4239.png)

**Comment by d33pspace** [comment]
@edwazhao Please comment with any further questions or close the issue.

**Comment by edwazhao** [comment]
Hi @MariiaBubley , yes, user can click the item catalogue, what if the T-SHIRT has more than one items, like short-sleeve t-shirt and long-sleeve t-shirt, how to decide which item is the use want to edit?
![image](https://user-images.githubusercontent.com/11383105/132270627-fd98c8f0-1ecf-4225-a865-6e52a1edcf62.png)

**Comment by MariiaBubley** [comment]
We decided with Jimmy before, t-shirt, shirt, pants et. - are the types of items. They are countable and added in the database by developer. Sleeveless, short-sleeve, long-sleeve et. - are the titles of items and name by admins(user) from New Item page https://d33pspace.github.io/RenewalMgtApp-Html/app/new_item.html
![image](https://user-images.githubusercontent.com/89512026/132522699-b2bcc4c9-702a-499a-8fb3-c9cd38d80a28.png)

**Comment by d33pspace** [comment]
Hi @edwazhao ... if I understand your meaning correctly, perhaps it is not clear how to edit items inside of types? There needs to be a way to edit both types and items. There also needs to be a way to add items, but not types. I believe we agreed that Types are hard-coded. Users cannot edit them.

**Comment by edwazhao** [comment]
Hi @d33pspace , yes, the Types and initial Items will be imported to database automatically, the data is coming from Miro https://miro.com/app/board/o9J_ko0nJTY=/. 

And yes, my question is how to edit items inside of types, is it allowed or not?
There are different naming here and there, I would like to confirm with you

the name under Policy is called： Types, Item Types, Item catalogue, right?
the item is the real thing we distribute to Guests.
![image](https://user-images.githubusercontent.com/11383105/132660609-24940c43-ccdf-485a-a813-e201bbe2869d.png)

Item Type's name&icon cannot be modified, but the days of distribution policy can be updated by editing the item belongs to it, is it correct? My original question how to edit the Item if we only show Item Types in the list?

**Comment by d33pspace** [comment]
Hi @edwazhao ... 

1. The "Item Catalogue" contains "Types" and "Types" contain "Items."
2. Types name and icon cannot be modified, but the distribution policy for the type can be updated by editing any item that belongs to it.
3. If a Type contains Items, Users can only distribute Items to Guests. 
4. If a Type does not contain Items (for example, "Shorts"), Users can distribute the Type to Guests.
5. Users should be able to edit Items, but there is no reason to edit a Type unless it does not contain an Item, in which case it must be able to be edited. 

It seems like 4 and 5 may present a logical problem. Do you agree?

**Comment by edwazhao** [comment]
Hi @d33pspace ,
Yes, from my perspective, there is a logical problem, Types name and icon cannot be modified, but a Type can be edited if  it does not contain an Item. 
I would like to make the logical easy to understand
1. Types name and icon cannot be modified
2. if Type does not contain an Item, we have to add a Item to the Type to modify the distribution policy
To move one more step further, I would suggest each Type must contain at least one Item, and we only distribute Item to Guest, in the real world we cannot give Type to Guest, we have to give the real Item.

My initial question is: which Item should be shown in edit mode when we tapping the Type line in https://d33pspace.github.io/RenewalMgtApp-Html/app/item_catalogue.html and the Type contains more than one Items? If I click T-shirt Type, there are several Items like short-sleeve, long-sleeve could be opened in Edit Item page, so which one?

**Comment by d33pspace** [comment]
Hi @edwazhao Got it.

If we agree that each Type contains at least one Item, there are times with the interface of the app that it would be a wasteful step to expand the Type to see only one Item. So in those cases, to the User it would look like they can give an Item to the Guest (as long as the Type has only one Item in it). Is this reasonable?

If so, I think the same should apply here. The user would be able to tap on the Type to edit it directly as long as there was only one Item in that Type. Or, if there was more than one Item in a Type, the Type would need to be able to expand first to show more choices. Do you agree?

**Comment by edwazhao** [comment]
Hi @d33pspace , yes, I agree, then we need to expand it if there are more items available in the Type, currently we don't have this function, right?

**Comment by d33pspace** [comment]
@MariiaBubley In the item catalogue ( https://d33pspace.github.io/RenewalMgtApp-Html/app/item_catalogue.html ) it seems we need a way to expand Types to display Items when Items need to be edited. Would you agree? (If a Type contains no Items, the Type can be edited directly.)

**Comment by edwazhao** [comment]
Hi @d33pspace , to your comment above:  (If a Type contains no Items, the Type can be edited directly.)
should we only make policy editable?

**Comment by d33pspace** [comment]
I believe "Can be washed" may be hardcoded so we do not need to make that editable, but ideally, we could edit "Active item" because, for example, we could turn that off in the winter.

**Comment by MariiaBubley** [comment]
@edwazhao @d33pspace 
I have added the opportunity to extend Type.
![image](https://user-images.githubusercontent.com/89512026/133371853-a2b5246a-79a0-4607-a5f7-bcddc4b1d59f.png)

**Comment by d33pspace** [comment]
@AnKar112 @academws The Figma model for Item Catalogue has been updated to include the ability to expand items to reveal sub-items. Please make the update to the HTML template.

**Comment by AnKar112** [comment]
Done. Check, please.

**Comment by d33pspace** [comment]
@MariiaBubley This seems okay to me. What do you think?

@edwazhao Is this sufficient for you? Do we need demonstration of tap to open link on Item or Type without Items?

**Comment by MariiaBubley** [comment]
@d33pspace 
https://d33pspace.github.io/RenewalMgtApp-Html/app/item_catalogue.html

I have few edits:
1)Not correct background
2)Why arrow is not changed? When line collapsed have to displayed grey down arrow, when line extended - black up arrow.
3)On this page work only one line, others do not extend.
4)Incorrect title

**Comment by d33pspace** [comment]
@MariiaBubley 

1) Please explain or provide screenshot.
2) Agreed.
3) I believe this is sufficient to demonstrate UI functionality. The rest can be handled by Edward. But we do need demonstration of a Type with no Items, such as shorts.
4) Agreed.

@academws @AnKar112 
- Please see Mariia's point 2 above. The arrow needs to change when a line expands.
- There are some items that will not expand, such as shorts. Please remove the arrow on that line to demonstrate this feature.
- Please change the title of the page to "Item catalogue"

**Comment by AnKar112** [comment]
Not correct background - fixed
arrows - fixed
about next one - this how I get it from design http://ipic.su/img/img7/fs/kiss_56kb.1631824265.png
and the page already have this title

**Comment by d33pspace** [comment]
@AnKar112 @academws 
Perhaps you are still working on this now, but this is what I am seeing in my browser (screenshot below). 
- header is messed up, 
- title of item_catalogue is incorrect. Right now it is "Behavior overview" it should be "Item catalogue. 
- thank you for explanation of other points, I will test further once these are corrected.
![Screenshot 2021-09-17 055239](https://user-images.githubusercontent.com/13606352/133690685-944fa93f-5f8c-4ee3-83e1-2c86fbe90b8a.png)
s

**Comment by AnKar112** [comment]
You must be checking while I was working on it. Header is ok now.

**Comment by d33pspace** [comment]
@MariiaBubley 
- Please confirm background is fixed.
- Is your intent that a Type with Items has a grey arrow when collapsed, then a black arrow when expanded? And a Type with no Items has no arrow?

**Comment by d33pspace** [comment]
@AnKar112 @academws 
(1) When the expand arrow is facing down, it should be grey. When it is facing up, it should be black. Our apologies if this is different from Figma.

(2) For demonstration purposes, Item Catalogue needs to have at least one row that does not have the down arrow because some items do not expand. Please demonstrate that (a) rows that do not expand open an external link by tapping anywhere on the row. And (b) items in rows that expand also open an external link by tapping anywhere on the row.

**Comment by MariiaBubley** [comment]
@AnKar112 
![image](https://user-images.githubusercontent.com/89512026/133743882-cbd5d93b-1c5f-4831-a640-5507ebbf5b79.png)

@d33pspace @AnKar112 
I find a new mistake, the header start started to move to the left.
![image](https://user-images.githubusercontent.com/89512026/133742100-4307209f-ca19-4509-b8f3-ecaf8c5b3756.png)

Also, I propose to make a shadow, which appears only when the scrolling starts. In default, the header is placed without shadow. (not only hear but on all pages. 
_Shadow (x=0, y=2, blure=8, #3A3C40, 16%)_
![image](https://user-images.githubusercontent.com/89512026/133743087-5ba913e5-b288-4aaa-99e9-f2a58f62d338.png)

Other cases did not resolve here.

**Comment by AnKar112** [comment]
(1) When the expand arrow is facing down, it should be grey. When it is facing up, it should be black. Our apologies if this is different from Figma. - done 

(2) For demonstration purposes, Item Catalogue needs to have at least one row that does not have the down arrow because some items do not expand. Please demonstrate that (a) rows that do not expand open an external link by tapping anywhere on the row. And (b) items in rows that expand also open an external link by tapping anywhere on the row. - done 

I find a new mistake, the header start started to move to the left. - F5 help with it?

Also, I propose to make a shadow, which appears only when the scrolling starts. In default, the header is placed without shadow. (not only hear but on all pages. - okay, have some problems with it. Box shadow used for all the box, we couldn't use box-shadow only for bottom. And it will be bad on desktop, in all sides: http://ipic.su/img/img7/fs/kiss_16kb.1631911393.png
There is one hack - if we make spread same as blur but negative (or plus-minus close to it) it will be only on one side. Check it now, it 0 2px 8px -6px #3A3C40 on scroll. I think, this is the best, what we can make. 
And next time send everything in pixels, please, there is no percentages in css box-shadow, this is only figma trick.

**Comment by d33pspace** [comment]
@MariiaBubley 
- What do you think about the shadow here? It looks good to me!
- Also, do you see any problems with header alignment on Mac? 
https://d33pspace.github.io/RenewalMgtApp-Html/app/item_catalogue.html

@AnKar112 @academws 
Changes look great! Thank you!
- Please remove the Search bar. You have it here correctly (it was in Figma) but I decided I don't want it on this page.
- Please demonstrate the full-line tap functionality like so:
![133755792-1d98da73-e46b-42e4-b015-631ccf5c85ff](https://user-images.githubusercontent.com/13606352/133867833-66f03218-f5fe-4bb6-9876-f9244486cc93.png)

**Comment by AnKar112** [comment]
Please remove the Search bar. You have it here correctly (it was in Figma) but I decided I don't want it on this page. - done
I've noticed the expand/collapse on take_page and give_page has a subtle animated effect and I like it. Can you implement it on this page also, please? - you mean arrow animation, right? done
Please demonstrate the full-line tap functionality like so: - done

**Comment by d33pspace** [comment]
@AnKar112 @academws 
Everything looks great except I still see the search bar at the top of the page. Please remove it.

**Comment by MariiaBubley** [comment]
@d33pspace 
![image](https://user-images.githubusercontent.com/89512026/133983318-785b2209-bc82-4cc8-8ec6-f86a64b11786.png)
After the search has to be padding 16px.

header alignment is fine
