### ISSUE TITLE
Missing service icon of Settings page

### ISSUE THREAD

**Issue by edwazhao** [d33pspace/RenewalMgtApp-Html#50]
https://d33pspace.github.io/RenewalMgtApp-Html/app/settings.html
1. Could you please add Service button ?
2. Could you please also add css for admin role?

![image](https://user-images.githubusercontent.com/11383105/142220931-6f59c9b0-7a9c-4071-a1a4-084f0301828e.png)

![image](https://user-images.githubusercontent.com/11383105/142221387-ed291cf8-3334-424d-9182-c3a23c2d0cf7.png)

@d33pspace , Here we have red A icon for volunteer role in settings page, see above picture, but normally we are using a red heart, please help to confirm.
![image](https://user-images.githubusercontent.com/11383105/142221951-103fe2db-b48c-41a3-9981-186de0c41280.png)

**Comment by AnKar112** [comment]
Done. I create settings admin page. 
Should I dublicate other settings pages ( this http://ipic.su/img/img7/fs/kiss_6kb.1637276520.jpg ). Them look simular.

**Comment by AnKar112** [comment]
Als, I changed icons color, border-radius and size, because it was changed in figma

**Comment by edwazhao** [comment]
Thanks, no need to create other settings page for admin.
