### ISSUE TITLE
Upload photo (edit_guest, edit_user pages)

### ISSUE THREAD

**Issue by d33pspace** [d33pspace/RenewalMgtApp-Html#51]
@AnKar112 
Please add template for photo cropper to edit_guest and edit_user_profile pages.

(1) I will ask Mariia about the border radius and hover. Feel free to wait for her response before you make further changes to this page.

(2) Please align the buttons and upload area for all browser widths.
![Screenshot 2022-01-21 121602](https://user-images.githubusercontent.com/13606352/150465087-823c20bb-4670-4f17-b382-85b20671ed07.png)
![Screenshot 2022-01-21 121649](https://user-images.githubusercontent.com/13606352/150465093-11c85ca6-f834-4c97-a470-3291d4e0448f.png)

**Comment by AnKar112** [comment]
(2) - done
After you approve everything is ok, I will do the same for edit_user_profile page

**Comment by d33pspace** [comment]
@AnKar112 
[Here](https://www.figma.com/file/3DZItCETG2QIvRYnlQvMyn/Renewal-Mobile-App?node-id=2499%3A60788) is the information for the buttons.

**Comment by AnKar112** [comment]
(1) - done
(2) - sorry for that, done too
Also, you can use class "disabled" on button for disabled state when you need it.

**Comment by d33pspace** [comment]
@AnKar112 
Looks great! Please add the same thing now for edit_user_profile.

**Comment by AnKar112** [comment]
Done
