### ISSUE TITLE
Header updates (multiple pages)

### ISSUE THREAD

**Issue by d33pspace** [d33pspace/RenewalMgtApp-Html#53]
@AnKar112 
(1) The following pages have updates ready in Figma [here](https://www.figma.com/file/3DZItCETG2QIvRYnlQvMyn/Renewal-Mobile-App?node-id=2362%3A27575) for header changes.

new_item
edit_item 
item_catalogue
settings_admin
settings_service
start_the_service 

(2) All user page headers have also been updated to black.

(3) Please disregard report pages for now. I am still discussing with Mariia.

**Comment by AnKar112** [comment]
(1) (2) - I checked all the pages from figma link, all headers must be done now. 
Layout changes from Mairia comments done too. 
Check it, please.

Also, we have no this 'blank' guest profile page https://i.imgur.com/Ob7FjEq.jpg
and no separate pages for 'edit user', 'edit profile' and settings-admin pages
Should I make it?

**Comment by d33pspace** [comment]
@AnKar112 
Everything looks great!

Yes, please go ahead and make a template for "blank" guest profile.

I will ask about the other ones. Thank you for pointing them out.

**Comment by AnKar112** [comment]
Done

**Comment by d33pspace** [comment]
@AnKar112 
I'm sorry a few additional changes here. The following pages need to have the header changed to black. Current models are [here](https://www.figma.com/file/3DZItCETG2QIvRYnlQvMyn/Renewal-Mobile-App?node-id=2362%3A27575).

edit_guest
guest_list
behavior_overview
guest_profile_history
guest_profile_item_lost
guest_profile
guest_profile_blank
new_guest
settings
settings_admin
settings_language
settings_notifications
settings_service

I am still working on the date selection on the reports with Mariia so do not worry about those for now.

**Comment by AnKar112** [comment]
Done for all these pages. Check it.
