### ISSUE TITLE
Disabled fields (edit_guest)

### ISSUE THREAD

**Issue by d33pspace** [d33pspace/RenewalMgtApp-Html#55]
@AnKar112 
Regarding [this](https://imgur.com/3GMsn91) issue.

Mariia's comments are:

This is not a placeholder, you cannot enter text here. Inside of this element text appears automatically when the user enters a name in Hanzi on the line above. Therefore, there is a background here, if the name is entered - green, if not entered - grey.

**Comment by AnKar112** [comment]
The styles part is done. For now, the field with ID 'pinyin' has #F1F2F4 background and is disabled for change.
If I understand you correctly, the work by automatic translation will be done by your developer. For changing the background to #DDF0EE , he should give a class 'filled' to this field.
