### ISSUE TITLE
Report design

### ISSUE THREAD

**Issue by d33pspace** [d33pspace/RenewalMgtApp-Html#56]
@AnKar112 
The report designs have been finalized, they are [here](https://www.figma.com/file/3DZItCETG2QIvRYnlQvMyn/Renewal-Mobile-App?node-id=2362%3A27575) on the bottom row.

The date picker is [here](https://material.angular.io/components/datepicker/overview#date-range-picker-overview).

And Mariia provides this capture for reference:
https://user-images.githubusercontent.com/89512026/151147639-2907b1da-523c-48c6-99a6-cc3e4305b221.mov

**Comment by AnKar112** [comment]
@d33pspace as I said to you here https://github.com/d33pspace/RenewalMgtApp-FE/issues/5#issuecomment-1004847509 I can't use Angular datepicker. 

If your developer uses Angular for this project - he could. But from my side I couldn't, I work only with HTML.

**Comment by AnKar112** [comment]
https://vcalendar.io/
We can use our old datepicker for report pages

https://vcalendar.io/examples/datepickers.html
"date range" example looking pretty simular to our design

**Comment by d33pspace** [comment]
@AnKar112 
Oh I'm sorry thank you for the correction.

Yes, I was perfectly happy with our old date-picker for report pages. Can you do your best to implement it with Mariia's other changes and we'll take a look?

**Comment by d33pspace** [comment]
@AnKar112 
Just wanted to make sure you saw my comment above in case we can also move this issue forward.

**Comment by AnKar112** [comment]
@d33pspace everything is fine, I will use Vue datepicker.
Can you please tell me in detail how datepicker should work? 
Because I can come up with different ways to make this http://ipic.su/img/img7/fs/kiss_32kb.1643385658.jpg
For example, "this week'. A week like literally this week? I mean, if you click on it on Monday, it will show only one day.
Or week like 7 days from today?

**Comment by d33pspace** [comment]
@AnKar112 
Good question. I'm glad you asked.

The only time the Vue datepicker will appear is when the User taps "Custom". When the user taps "Custom" the datepicker will appear. It can be blank at first, and the User can choose either one day, or a range of dates. If they choose one day, the same date is entered in both the beginning and end date fields. If they choose a range, the start date is entered in the start date field, and the end date is entered in the end date field. 

For the six suggested date ranges (Today, Yesterday, This Week...) the datepicker does not need to appear. When the User taps one of these, the dates can be directly entered into the beginning and end date fields. I don't know if this is your job, or Edwards, but for "This week" and "Last week" we will use the dates beginning Sunday and ending Saturday.

Just let me know if you need more information.

**Comment by AnKar112** [comment]
@d33pspace I can't get styles from figma, because an image is above all datepicker http://ipic.su/img/img7/fs/kiss_99kb.1643622204.jpg
Could you ask Maria to remove it?

**Comment by AnKar112** [comment]
Everything is done, except: 
(1) - We have no pages Unfulfilled requests and Items we trashed. It looks totally the same as Item we lost. Should I just dublicate Item we lost ?
(2) datepicker styles - still waiting for http://ipic.su/img/img7/fs/kiss_99kb.1643622204.jpg

Check report pages and give me your feedback, please.

**Comment by d33pspace** [comment]
@AnKar112 
(1) If everything is the same, I don't think you need to create the template, I think Edward can just do that himself. Don't you agree?
(2) The date-picker looks great to me! I am waiting on Mariia to confirm.

**Comment by d33pspace** [comment]
@AnKar112 

Mariia has made some updates to the styles for the reports, date-picker, her comments are below... I do not really understand all of it. If there is something you do not understand just let me know and I will ask her.

[Here](https://www.figma.com/file/3DZItCETG2QIvRYnlQvMyn/Renewal-Mobile-App?node-id=2362%3A27575) I made mockup with styles 
![image](https://user-images.githubusercontent.com/89512026/152118305-c6393a2c-dcfe-4910-aa77-59f905f8ff91.png)

I also have edits for [this](https://d33pspace.github.io/RenewalMgtApp-Html/app/reports_behavior.html) page:
Go [here](https://www.figma.com/file/3DZItCETG2QIvRYnlQvMyn/Renewal-Mobile-App?node-id=2362%3A27575) and read comments 
![image](https://user-images.githubusercontent.com/89512026/152120279-6bbf587a-faa8-44e5-95dc-76c3a4c670b9.png)

and also ask Anton to use hover for active elements
![image](https://user-images.githubusercontent.com/89512026/152120445-5a6863fe-ed33-46bb-85a1-a0590c4ffb4c.png)

**Comment by AnKar112** [comment]
Everything is done.
