### ISSUE TITLE
Clean up all HTML templates

### ISSUE THREAD

**Issue by d33pspace** [d33pspace/RenewalMgtApp-Html#58]
From Anton:

---

I'd like ask you about improving the code.
When there are so many design changes, there is a chance that some unused styles or JS-strings will be left in files. I clean it when I work, but I can miss something.
I'd like you to have a clear code. Could you, please, set me a task to check all the files once the redesign will be finished?
I'd like to double-check everything on the final version.

**Comment by d33pspace** [comment]
@AnKar112 
All the work you have done has been great, thank you!

This thread is just to remind you that you asked for some time to clean up the files before we have Edward integrate them into the app. 

Before you do, I want to say that while I think all of the major changes are finished now, I am still going to have Mariia review all the templates, and I still have quite a bit of testing to do to the app so I know both of us are going to find other things that need to be changed. However, they will not be so major like the ones you've been working on these last few weeks.

If you'd like to start now to clean up the code, please feel free and take all the time you need. But if you'd like for us to complete testing first, that's also fine. I can remind you again later.

**Comment by AnKar112** [comment]
Everything is checked, must be good. 
Also. we have a problem. Vue datepicker didn't load, give 404 mistake https://i.imgur.com/FGyzTXj.jpg
I hope this is temporary issue, let's wait

**Comment by d33pspace** [comment]
@AnKar112 
Everything looks great, Anton. I see that the datepicker on the report pages is not working. Is this what you mean by it "didn't load"? Can you check on this again today? I thought it was working fine before - did we lose that?

**Comment by AnKar112** [comment]
(1) - we use Vue datepicker. Looking vike Vue was updated, so the calendar module become broken, and it didn't load properly. 
Let's wait, I hope the guide here https://vcalendar.io/installation.html will be updated for the new Vue version
(2) - should I delete the files for burger_opened too, or just only delete the link from index.html?

**Comment by d33pspace** [comment]
@AnKar112 

(1) Alright, I'll discuss with Edward. Perhaps he can begin working on other pages and import the report pages later.

(2) I think just deleting the links from index is sufficient. This way it will be clear to Edward which pages have been updated. Thank you!

**Comment by edwazhao** [comment]
@AnKar112 
For 404 when loading vue.js, maybe you can try to use different CDN, for example https://cdn.jsdelivr.net/npm/vue@3.2.31

**Comment by d33pspace** [comment]
@AnKar112
Now that @edwazhao will begin importing the updated templates into our app, I will close all the issues in this repository (including this one) and any future issues will be handled in the front-end repository. I'll be careful to keep your issues clear. This particular issue with the Vue datepicker we will continue discussing [here](https://github.com/d33pspace/RenewalMgtApp-FE/issues/44).
