### ISSUE TITLE
Items under types

### ISSUE THREAD

**Issue by d33pspace** [d33pspace/RenewalMgtApp-Html#59]
@AnKar112 
Mariia has updated the look of items under types for the following pages. There is no longer space or shading.

item_catalogue
give_page
take_page

For example:
![Screenshot 2022-02-01 093324](https://user-images.githubusercontent.com/13606352/151900291-8af3c93d-bee9-40a1-851b-ec2d8f2a9c4b.png)

**Comment by AnKar112** [comment]
Done
