### ISSUE TITLE
Update role with dropdown

### ISSUE THREAD

**Issue by d33pspace** [d33pspace/RenewalMgtApp-Html#6]
This Figma mock-up has been updated with role as a dropdown - please update the HTML template.

![Screenshot 2021-09-06 160632](https://user-images.githubusercontent.com/13606352/132182555-217ca9e1-ced0-4d10-a695-6a8c06db4202.png)

**Comment by d33pspace** [comment]
@edwazhao This appears to have been updated. Can you confirm this is acceptable?

Edit user profile: https://d33pspace.github.io/RenewalMgtApp-Html/app/edit_user_profile.html

**Comment by edwazhao** [comment]
Thanks.
