### ISSUE TITLE
Delete Guest

### ISSUE THREAD

**Issue by d33pspace** [d33pspace/RenewalMgtApp-Html#60]
Hi @AnKar112 
I'm sorry I just now noticed this, and for some reason these designs didn't make it to our final ones, but the Edit Guest page needs a trash can in the upper-right corner so the User can delete the Guest if necessary. There is also a confirmation pop-up window.

Can you add this, please?

Design here:
https://www.figma.com/file/3DZItCETG2QIvRYnlQvMyn/Renewal-Mobile-App?node-id=2351%3A101636

**Comment by AnKar112** [comment]
Done
