### ISSUE TITLE
Meal icon issue in give page

### ISSUE THREAD

**Issue by edwazhao** [d33pspace/RenewalMgtApp-Html#61]
https://d33pspace.github.io/RenewalMgtApp-Html/app/give_page.html

When using Phone mode, the meal icon cannot be unchecked.

![image](https://user-images.githubusercontent.com/11383105/156921350-af30d621-f2fb-41b7-842e-c77609230b6a.png)

**Comment by edwazhao** [comment]
Hi @d33pspace , please help to check if we need the un-check meal icon here?

**Comment by d33pspace** [comment]
Hi @AnKar112 How are you? I hope you're staying safe. We are all behind you. 

Can you please check the issue above. Also, will you see if the Vue calendar has been updated?

**Comment by AnKar112** [comment]
It works as it should - uncheck working fine. 
But after you uncheck it, 'finger' is still on the button, so you see hover styles https://i.imgur.com/gHMZsWD.jpg
Should I delete hover styles? 

Calendar - still the same

**Comment by d33pspace** [comment]
@AnKar112 
Thanks Anton - may I ask is it possible that the Vue calendar has been deprecated? And in any case, what do you suggest if it is not updated in time? We really hope to launch the app as soon as possible.

**Comment by AnKar112** [comment]
Let's try another way
@edwazhao is it possible for you to use calendar throw npm? https://vcalendar.io/installation.html

**Comment by d33pspace** [comment]
@edwazhao 
Please see Anton's reply to the meal button issue as well as the calendar issue above.

**Comment by d33pspace** [comment]
@AnKar112 
I agree with Edward, the current design is not suitable for mobile browser. Perhaps Mariia did not understand that mobile browser is our main interface. Please fix this, and I wonder if we need to change other hover actions as well?

Also check Edward's work on the calendar. The current calendar/date-picker on the reports_operations page looks great to me!

**Comment by AnKar112** [comment]
About hovers - I removed it for mobile resolutions (769px and less). So on the desktop you still have hovers. 
Should I check all pages for hovers?

About the calendar - great job, thank you!

**Comment by d33pspace** [comment]
@AnKar112 
Yes, please check all pages for hovers and remove them for mobile resolutions. Please post a list here of the files that are changed. Thank you!

**Comment by AnKar112** [comment]
forgot_password.html - button
give_page.html - FAB, cards hover
main_page.html - serve button
password_recovery.html - button 
password_recovery_success.html - button
reports_behavior.html, reports_item_lost.html, reports_behavior_overview.html, reports_operations.html - datepicker button, datepicker options
return_page.html - buttons, fab
sign_in.html, sign_up.html - button
take_page.html - FAB, cards hover
success.html - button

Also, I use calendar fix for all pages

**Comment by d33pspace** [comment]
@edwazhao 
Please note the pages here with updated hovers and datepickers. Please let us know if you need anything else here.

**Comment by edwazhao** [comment]
Everything looks good, I will close it.
