### ISSUE TITLE
Report/Operations body will cover title when scroll

### ISSUE THREAD

**Issue by edwazhao** [d33pspace/RenewalMgtApp-Html#63]
https://d33pspace.github.io/RenewalMgtApp-Html/app/reports_operations.html

See
![image](https://user-images.githubusercontent.com/11383105/157037322-a4c7bee5-81ec-435e-8a1b-3385c30f5314.png)

**Comment by edwazhao** [comment]
Hi @d33pspace , please help to check this issue

**Comment by d33pspace** [comment]
@AnKar112 
Please fix the issue above.

**Comment by d33pspace** [comment]
@edwazhao 
This looks good to me. Do you agree?

**Comment by edwazhao** [comment]
Yeah, looks good.
