### ISSUE TITLE
SCSS complains fill-available

### ISSUE THREAD

**Issue by edwazhao** [d33pspace/RenewalMgtApp-Html#64]
Hi Anton, 
During the npm build, it complains that:

`Replace fill-available to stretch, because spec had been changed`

I think it is located in start_the_service.scss, I have changed it from `width: fill-available` to `width: stretch`, I don't understand the setting, so could you please confirm it works as expected?

**Comment by AnKar112** [comment]
I changed `width: fill-available` to `width: 100%` in start_the_service
