### ISSUE TITLE
Chinese translation problem

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalMgtApp-Html#65]
Some Chinese are not translated properly. Please correct them as below,
1. 登陆 --> 登录  
<img width="194" alt="image" src="https://user-images.githubusercontent.com/42002784/158980764-3bf9241f-7c6c-4445-bcfa-4340912325f3.png">

2. 中国人 --> 中文 
<img width="187" alt="image" src="https://user-images.githubusercontent.com/42002784/158980720-58f49a40-80a5-4b65-a66f-db5f8306ce9d.png">

3. 仍 --> 扔
<img width="382" alt="image" src="https://user-images.githubusercontent.com/42002784/158980824-5b636eff-79da-4d1c-835c-905e2f476239.png">

4. 年 --> 岁
<img width="270" alt="image" src="https://user-images.githubusercontent.com/42002784/158985778-e1902b74-9a12-4ddd-b5ff-1bc58504972e.png">

5. 改 --> 该 
<img width="397" alt="image" src="https://user-images.githubusercontent.com/42002784/158986206-4bbe70f8-b02a-48b2-84a1-e5cdae164e52.png">

**Comment by edwazhao** [comment]
@elainetao829 , fixed.

**Comment by elainetao829** [comment]
Verified successfully.
