### ISSUE TITLE
The user edit page is not completely translated into Chinese.

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalMgtApp-Html#66]
The user edit page is not completely translated into Chinese, even I select the language as Chinese, they are still in English. See below,
<img width="431" alt="image" src="https://user-images.githubusercontent.com/42002784/158981185-4c358545-465a-4631-9a18-7fa4acecec9f.png">

<img width="330" alt="image" src="https://user-images.githubusercontent.com/42002784/158981528-9e4dbf18-c38f-41bb-b240-cf83c05e1d5c.png">
 
<img width="374" alt="image" src="https://user-images.githubusercontent.com/42002784/158981702-3fc9d7a6-43c0-4ba6-9005-5eafa2b002f6.png">

**Comment by edwazhao** [comment]
It is fixed, please check.

**Comment by elainetao829** [comment]
Verified successfully.
