### ISSUE TITLE
The date widget is extremely not user friendly when user opens the system with a laptop.

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalMgtApp-Html#67]
It's really hard to select a year with a mouse.
https://user-images.githubusercontent.com/42002784/158985041-1067a161-9aa4-4eac-a800-a46dd73d2799.mp4

**Comment by d33pspace** [comment]
This is a known issue and since we'll be using mobile devices exclusively at the drop-in center we will deal with it later.

**Comment by d33pspace** [comment]
@elainetao829 Please move this to the FE repository and label it as "minor."

**Comment by d33pspace** [comment]
I'm closing this and moving it to the FE repository.
