### ISSUE TITLE
The numbers of in-service capacity/duration and waiting duration shall be >= 0

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalMgtApp-Html#68]
The numbers of in-service capacity/duration and waiting duration shall be >= 0
<img width="372" alt="image" src="https://user-images.githubusercontent.com/42002784/159024101-7c204abb-7dfd-4c4c-951b-3c592d414b00.png">

**Comment by edwazhao** [comment]
fixed.

**Comment by elainetao829** [comment]
Verified successfully
