### ISSUE TITLE
After deleting a user account, the user still can log in.

### ISSUE THREAD

**Issue by elainetao829** [d33pspace/RenewalMgtApp-Html#69]
Steps:
1. Log in as an admin.
2. Deleting one user account.
3. Log out the admin account.
4. Log in with the account deleted in step 2.

Actual Result:
User can still log in with the deleted account. And the buttons are still enabled after log in.

https://user-images.githubusercontent.com/42002784/159025639-63f60584-ec4b-4f4e-82dd-6cb55be3cfb6.mp4

Expected Result:
Deleted account shall not be able to be logged in any more.

**Comment by edwazhao** [comment]
Fixed

**Comment by elainetao829** [comment]
Verified successfully.
