### ISSUE TITLE
Loader page

### ISSUE THREAD

**Issue by d33pspace** [d33pspace/RenewalMgtApp-Html#7]
We just need a loader page with a spinner like this in the middle: https://uxfan.com/vue-easy-spinner/

I like the circular spinner. And we can use our logo color which is:
R: 209
G: 18
B: 65

**Comment by d33pspace** [comment]
@edwazhao Loader page has been added. If it's suitable please close this issue.

**Comment by edwazhao** [comment]
Hi @d33pspace , sure, please also update the index.html
