### ISSUE TITLE
Remove text-transform: capitalize;

### ISSUE THREAD

**Issue by edwazhao** [d33pspace/RenewalMgtApp-Html#71]
Please remove all the text-transform: capitalize;

Since we need customized text of Item names, the css makes it difficult to maintain, please remove all of them, I have removed them in FE repo, please help to do the same for HTML repo, thanks.

No rush on this.

**Comment by AnKar112** [comment]
Done

**Comment by d33pspace** [comment]
@edwazhao 
Please confirm at your convenience.

**Comment by edwazhao** [comment]
Looks good, thank you.
