### ISSUE TITLE
Please correct the report file name with correct content

### ISSUE THREAD

**Issue by edwazhao** [d33pspace/RenewalMgtApp-Html#72]
Sorry, it confused me every time. See:
![image](https://user-images.githubusercontent.com/11383105/159104292-8e38e2f5-7b61-4011-ab3c-b3d08c84aac2.png)
![image](https://user-images.githubusercontent.com/11383105/159104305-a9725a7c-5c55-4502-a86a-51403c1d0db6.png)

**Comment by AnKar112** [comment]
@d33pspace As I can see, all report pages have this problem with naming. I'm confused a little - what to orientate towards?
Can you clarify how should I name these pages?

**Comment by d33pspace** [comment]
@AnKar112 
Hi Anton! Let's go with the file name same as the heading of the report. So rename like this:

reports_operations.html > reports_distribution.html
reports_behavior.html > reports_operation.html

Please also correct the <title>

**Comment by AnKar112** [comment]
Check it, must be good now

**Comment by d33pspace** [comment]
@edwazhao 
Please take a look that the new filenames are what you intended.

**Comment by edwazhao** [comment]
Looks good, thank you.
