### ISSUE TITLE
Unify search

### ISSUE THREAD

**Issue by d33pspace** [d33pspace/RenewalMgtApp-Html#75]
@AnKar112 
I'm sorry I just noticed we don't have a persistent search field on guest_list or start_the_service.

Can you please implement [Mariia's design](https://www.figma.com/file/3DZItCETG2QIvRYnlQvMyn/Renewal-Mobile-App?node-id=2362%3A27575) on these two pages? She says this is "[persistent search](https://material.io/design/navigation/search.html#persistent-search)" by Material Design. Actually, she suggested "expandable search" for guest_list, but I want persistent search on both guest_list and start_the_service.

![159881800-ea3d2b07-97a9-486c-875a-10c86943f1a6](https://user-images.githubusercontent.com/13606352/159886153-b37da6ec-04a5-4182-b480-b72bf80272e5.png)

**Comment by AnKar112** [comment]
@d33pspace I should only make layout, not the functional, right?
And by the way, we also have the buttons 'search' on guest list, user list, and item catalogue.

**Comment by d33pspace** [comment]
@AnKar112 
Yes, layout only.

- I would like persistent search on guest_list and start_the_service
- user_list can have either persistent search or expandable search. Expandable search is my preference, but if it takes a lot more time, let's do persistent search.
- Please remove the search button on item catalogue. It's not necessary.

Let me know if you need a design for any of these. Mariia has designs for both persistent search and expandable search, but only on guest_list (expandable) and start_the_service (persistent).

**Comment by AnKar112** [comment]
https://material.io/design/navigation/search.html#persistent-search - this is not really what can I do. I didn't think that material design is a guide for developers at all. As I know, devices have their own styles of search dropdown menu. Android, iOs - they have their own styles. Maybe @edwazhao knows more about that.

**Comment by d33pspace** [comment]
@AnKar112 
Our app is a web app, not Android or iOS. Are you able to add the search start_the_service page like in Mariia's design on Figma? That is most important.

**Comment by AnKar112** [comment]
Okay, I will make the layout. But I can't find dropdown styles in figma, like that https://i.imgur.com/aO3GpfA.jpg can you give me a direct link?

**Comment by d33pspace** [comment]
@MariiaBubley 
The following pages have Search, and this is how I'd like the search fields on those pages:

(1) [guest_list](https://d33pspace.github.io/RenewalMgtApp-Html/app/guest_list.html) (Persistent search)
(2) [start_the_service](https://d33pspace.github.io/RenewalMgtApp-Html/app/start_the_service.html) (Persistent search)
(3) [user_list](https://d33pspace.github.io/RenewalMgtApp-Html/app/users_list.html) (Expandable search)
(4) [item_catalogue](https://d33pspace.github.io/RenewalMgtApp-Html/app/item_catalogue.html) (Remove search)

Also note that Anton needs the full design, not just reference to Material design. Including the dropdown style like this:

![aO3GpfA](https://user-images.githubusercontent.com/13606352/160218781-2dda4640-3c6d-40df-af97-f814a1a9ad0b.jpeg)

**Comment by edwazhao** [comment]
@d33pspace  @academws 
I am not sure about the difference of Persistent search and Expandable search. 
For the [guest_list](https://d33pspace.github.io/RenewalMgtApp-Html/app/guest_list.html) (Persistent search), does it mean we don't load anything for the guest_list page when first go the page?

From my point of view, if user type anything in the search area below, the list will also be updated based on the input directly, and it could be applied for every page with the search function.
![image](https://user-images.githubusercontent.com/11383105/160239947-c9be9e50-523b-4467-b02c-18b27dffb11c.png)

**Comment by d33pspace** [comment]
@AnKar112 
Edward has a good point here. There is no dropdown style necessary. The list will update based on what is entered in the search field. Knowing this, are you able to make the updates to the necessary pages without Mariia's new design?

**Comment by AnKar112** [comment]
Good idea. But I am confused a little - on page "Headers" in Figma we have two "Guest Lists" with a different design of search:

https://i.imgur.com/eUCOjBK.jpg
https://i.imgur.com/bh46csW.jpg
 
And by the way, "Headers" page becoming very huge, let's stop using it. It becoming hard to find something there.

**Comment by AnKar112** [comment]
Done, take a look.

**Comment by d33pspace** [comment]
@AnKar112 
Fantastic!
