### ISSUE TITLE
Return page missing "Return all" checkbox

### ISSUE THREAD

**Issue by d33pspace** [d33pspace/RenewalMgtApp-Html#76]
@AnKar112 
I also noticed the "Return all" checkbox was missing in our new design on the Return page. Mariia has corrected it [here](https://www.figma.com/file/3DZItCETG2QIvRYnlQvMyn/Renewal-Mobile-App?node-id=2362%3A27575).

![159879587-234525a6-0ba8-463b-aca1-5337a59a2fe5](https://user-images.githubusercontent.com/13606352/159888725-6440aab1-f216-4f1e-b0dc-b00d54da49c7.png)

**Comment by AnKar112** [comment]
Done
