### ISSUE TITLE
Update to item_catalogue

### ISSUE THREAD

**Issue by d33pspace** [d33pspace/RenewalMgtApp-Html#77]
@AnKar112 
We are updating the design of item_catalogue to make it more user friendly. New design [here](https://www.figma.com/file/3DZItCETG2QIvRYnlQvMyn/Renewal-Mobile-App?node-id=2362%3A27575).

<img width="561" alt="159893598-1a3165a1-3da3-4b8e-acc6-b6d7e998ba32" src="https://user-images.githubusercontent.com/13606352/159893908-1ac589b0-3f8b-4676-a10a-5333a66a2a72.png">

**Comment by AnKar112** [comment]
If I get everything right, done. Check it please.

**Comment by d33pspace** [comment]
@AnKar112 
Looking good! Just a few things...

(1) The Active/Inactive indicator needs to also be on Items.
(2) There may be stars on Types that do not expand.
(3) Please align the washing machine icons if possible. 

Also note that ALL rows (Types and Items) will have Active/Inactive indicators. But the washing machine and star icons will only appear on rows according to the settings of those Types or Items. (I just want to make sure the washing machines and stars can not appear if necessary.)

![Screenshot 2022-03-26 084320](https://user-images.githubusercontent.com/13606352/160218195-2172b781-a48d-4ad4-b4b7-fa48f98297c6.png)

**Comment by AnKar112** [comment]
Check it again, must be good now

**Comment by d33pspace** [comment]
@AnKar112 
Perfect!
