### ISSUE TITLE
Change Guest and User default icon

### ISSUE THREAD

**Issue by d33pspace** [d33pspace/RenewalMgtApp-Html#78]
@AnKar112 
Let's please change the default icon for [new_guest](https://d33pspace.github.io/RenewalMgtApp-Html/app/new_guest.html), etc. to this style. Design in Figma is [here](https://www.figma.com/file/3DZItCETG2QIvRYnlQvMyn/Renewal-Mobile-App?node-id=680%3A1100). This will apply to new_guest, edit_guest, user_profile, users_list, guest_list and other pages - anywhere there is a user or guest without photo uploaded.

![159897258-f3de27aa-fc65-44fb-a771-d7947427deab](https://user-images.githubusercontent.com/13606352/159904280-5e96630f-a655-442c-88af-ad145c956bd1.png)

**Comment by AnKar112** [comment]
Can Mariia give me this picture in 96x96 resolution, please?

**Comment by AnKar112** [comment]
Done, but I found blank avatar pictures only in new_guest and main_page
