### ISSUE TITLE
Add hat Type

### ISSUE THREAD

**Issue by d33pspace** [d33pspace/RenewalMgtApp-Html#79]
@AnKar112 
Add a Type for Hat on item_catalogue using this icon which is available in Figma [here](https://www.figma.com/file/3DZItCETG2QIvRYnlQvMyn/Renewal-Mobile-App?node-id=673%3A2851).

![159896809-6acf0327-ceb8-45da-8dc9-b6190aef2f85](https://user-images.githubusercontent.com/13606352/159904992-a2df5019-7b05-4f49-9de8-7ebfc83ea4c0.png)

**Comment by AnKar112** [comment]
Done
