### ISSUE TITLE
Do we have user list html?

### ISSUE THREAD

**Issue by edwazhao** [d33pspace/RenewalMgtApp-Html#8]
![image](https://user-images.githubusercontent.com/11383105/132235608-ea2fa8ed-1f24-4703-81e2-6cf46bf13eb2.png)

**Comment by d33pspace** [comment]
@edwazhao There appears to be Users list now. Is this what you were looking for?

Users list: https://d33pspace.github.io/RenewalMgtApp-Html/app/users_list.html
