### ISSUE TITLE
Change "Not found" icon

### ISSUE THREAD

**Issue by d33pspace** [d33pspace/RenewalMgtApp-Html#80]
The "Not found" icon on the [give page](https://d33pspace.github.io/RenewalMgtApp-Html/app/give_page.html) is a trash can. This doesn't make sense. "Not found" means that the Guest asks for something, for example, a pair of pants, but we do not have any in inventory. So the icon should be maybe a magnifying glass with an X? Or a sad face with Xs for eyes? I could not find something in our icon collection.

![Screenshot 2022-03-25 072608](https://user-images.githubusercontent.com/13606352/160026131-378e5516-4b82-4061-8613-b3fc02ce5b5b.png)
![1178479](https://user-images.githubusercontent.com/13606352/160026424-406c5f3a-a480-4e68-b578-8d65af596425.png)
![not-found-icon-design-line-style-perfect-application-web-logo-presentation-template-not-found-icon-design-line-style-169941512](https://user-images.githubusercontent.com/13606352/160026427-5714a166-66fa-4114-846a-ba0e16379a81.jpg)

**Comment by MariiaBubley** [comment]
@d33pspace "not found" in mockups - is an alert triangle

![image](https://user-images.githubusercontent.com/89512026/160113495-48452cd8-6e44-476c-8811-c615534d06e6.png)

But if you want, I can change it on this one
![image](https://user-images.githubusercontent.com/89512026/160119637-1fca4faa-76bd-4c73-915a-616ec4ea0bf0.png)

**Comment by d33pspace** [comment]
@AnKar112 
We are changing the "Not found" icon from trash can to magnifying glass with X, as shown above. Please make the change to give_page. (This only appears on give_page.)

**Comment by AnKar112** [comment]
Done

**Comment by d33pspace** [comment]
@AnKar112 
So cool!
