### ISSUE TITLE
Update "suit coat" icon

### ISSUE THREAD

**Issue by d33pspace** [d33pspace/RenewalMgtApp-Html#81]
@AnKar112 
Please update the suit coat icon to look like [this](https://www.figma.com/file/3DZItCETG2QIvRYnlQvMyn/Renewal-Mobile-App?node-id=2362%3A27575)...

![suit](https://user-images.githubusercontent.com/13606352/161877082-814cd09a-8163-4f1f-bd18-786755e982db.png)

**Comment by AnKar112** [comment]
Done

**Comment by d33pspace** [comment]
@AnKar112 
Thank you!
