### ISSUE TITLE
Change report icon colors

### ISSUE THREAD

**Issue by d33pspace** [d33pspace/RenewalMgtApp-Html#82]
Hi @MariiaBubley ...

Just a tiny change here. We need to reverse the color of the icons and text for increase and decrease. In China red is the good color and green is the bad color, so increase here needs to be red, and decrease needs to be green. The same is true for the clocks on the same report, increase in time should be green (because that's bad), decrease in time should be red (good).

This change is only necessary because we need the bar graph icons in the new colors.

![Screenshot 2022-04-13 145740](https://user-images.githubusercontent.com/13606352/163118426-825dcb5b-20f1-453c-924d-5d1ffa8168c5.png)

**Comment by edwazhao** [comment]
Hi @d33pspace ,
To your description
> In China red is the good color and green is the bad color

From my point of view, it is not the case, green means good, red mean bad, @elainetao829 what your opinion?
Same color used in notifications, green means success, and red means error
![image](https://user-images.githubusercontent.com/11383105/163179963-6b0b402e-3b8b-4143-8835-2117c23a957e.png)

**Comment by d33pspace** [comment]
@edwazhao 
Ah. Interesting. I am thinking of stock market reports. Red numbers are good. Green numbers are bad. @elainetao829 What is your opinion for our reporting? My current opinion is for alerts, red is failure, green is success. For reporting, red is good, green is bad. I don't think it's confusing because the context is different.

**Comment by edwazhao** [comment]
@d33pspace By the way, beside increase and decrease icons, do we need an equals icon? And what color for equals?
