### ISSUE TITLE
Reporting icons/colors update

### ISSUE THREAD

**Issue by d33pspace** [d33pspace/RenewalMgtApp-Html#83]
Hi @MariiaBubley 

We need just a few updates on our reporting icons and colors... see screenshot below...

(1) I believe the icon for the Distribution report (appears on Reports main page, and Distribution Report page, first column) should be the Give clothing icon (roll of clothing with stars over it) like on the Give page. Do you agree?

(2) The "Unfulfilled requests" icon should be the magnifying glass with X in it. This appears on Reports main page, and Distribution Report page, third column).

(3) We would like to swap the red and green colors on the Operation Report. Increase in Guests should be Red, decrease should be Green. Increase in time should be green. Decrease in time should be green. This is due to normal colors on reports in China. Red is often associated with positive trends.

![Screenshot 2022-04-19 121740](https://user-images.githubusercontent.com/13606352/163919218-06f05394-f449-4300-8e7b-8eca55936e97.png)

**Comment by MariiaBubley** [comment]
@d33pspace  Mockup [here](https://www.figma.com/file/3DZItCETG2QIvRYnlQvMyn/Renewal-Mobile-App?node-id=2976%3A50734)
(1) Yes, changed
(2) Changed
(3) I suggest using just two icons - chart and clock - chart describe quantity, hours - time. And the colour (together with the text after the icon) shows the trend. Red - growth, green - decline, yellow - static. 

![image](https://user-images.githubusercontent.com/89512026/164002210-40ab78f7-9613-4dc7-8150-392f9bfa5c4f.png)

**Comment by d33pspace** [comment]
Hi @AnKar112 
We have just a few small changes to icons on a few reporting pages with details above and new designs by Mariia [here](https://www.figma.com/file/3DZItCETG2QIvRYnlQvMyn/Renewal-Mobile-App?node-id=2976%3A50734).

**Comment by AnKar112** [comment]
Done
