### ISSUE TITLE
List button widths on Guest Profile page

### ISSUE THREAD

**Issue by d33pspace** [d33pspace/RenewalMgtApp-Html#84]
@AnKar112 
Hi Anton, just a small problem on the Guest Profile page. It seems that the List buttons (In-Service, Waiting, Finished) are tied to the width of the elements above them, but this can produce odd results based on the content (see screenshots). Can we make the row of list buttons independent? Edward suggests 60% of width of the screen on desktop, or 80% for mobile - or you can stick to Mariia's design or your own idea.

![164742763-29e3d50f-90e4-4ddd-85ac-e4fb422e16fe](https://user-images.githubusercontent.com/13606352/164816066-1cac3446-3fad-4294-b3a3-077e536cc7a1.png)

![164742969-533dc05a-b498-4f38-90d2-42487b10244e](https://user-images.githubusercontent.com/13606352/164816076-4ea53cbd-a16a-44a1-8060-edc60c546cc6.png)

**Comment by AnKar112** [comment]
60% for desktop, 80% for mobile - done
