### ISSUE TITLE
Take page

### ISSUE THREAD

**Issue by d33pspace** [d33pspace/RenewalMgtApp-Html#86]
Hi @AnKar112 ... Your work on the Give and Take pages was perfect! Thank you. I just have one question about the Take page.

When the take page is opened, the clothing tag confirmation modal appears. I tested changing the tag number, but the tag number on the Take page is not changed when I do this. Because I'm not a developer I don't know if this is something you do, or something Edward, our back-end developer does. 

If it's in your scope, please make the update. If not, just let me know. 😊

**Comment by AnKar112** [comment]
Done

**Comment by d33pspace** [comment]
Perfectly executed, @AnKar112 . Thanks!
